### ISSUE TITLE
Cant modify the email

### ISSUE THREAD

**Issue by Ruakker** [hydro-dev/Hydro#103]
![](https://gitee.com/chocola4ever/drawing-bed/raw/master/images/1.png)

无法更改电子邮件。

在填写正确密码以及正确电子邮箱后，显示“字段 currentPassword 验证失败”

**Comment by Ruakker** [comment]
发送的电子邮件貌似仍然有问题？网址不太对

![](https://gitee.com/chocola4ever/drawing-bed/raw/master/images/20210421170149.png)

**Comment by undefined-moe** [comment]
@wuxianucw 你的锅

**Comment by eventlOwOp** [comment]
undefined咋这么强
