### ISSUE TITLE
题目测试数据识别有误

### ISSUE THREAD

**Issue by IUaenaSong** [hydro-dev/Hydro#104]
一道题目我先是上传了 32 组测试用例，随后将其全部删除，之后重新上传了 10 组测试用例，但是在评测时还是显示 32 组，并且导致了错误
![1](https://user-images.githubusercontent.com/48179733/115404889-4f6b0900-a220-11eb-8c15-d3bd54a0b625.png)
![2](https://user-images.githubusercontent.com/48179733/115404900-50039f80-a220-11eb-9c48-e71b857a970a.png)
```
type: default
time: 3s
memory: 256m
checker_type: default
```
之后无论如何删除都是识别 32 组测试用例

**Comment by undefined-moe** [comment]
已在 hydrojudge@2.5.9 版本修复。   
请注意：您需要手动删除测试数据缓存（通常位于 `~/.cache/hydro/judge` ）以应用此更改。
