### ISSUE TITLE
评测记录页中，其他页的评测任务被抓取后会出现在顶部

### ISSUE THREAD

**Issue by Macesuted** [hydro-dev/Hydro#110]
![image](https://user-images.githubusercontent.com/57275149/115645265-a3760a80-a352-11eb-9d49-1c95871cb8be.png)

顶端显示正在评测的提交为后面几页正在评测的提交。刚进入评测记录页时不会显示该提交，该提交被评测机抓取后就会出现在顶部。

---

同时当用户在指定过滤条件后也会出现此类情况：

![image](https://user-images.githubusercontent.com/57275149/115645463-02d41a80-a353-11eb-977d-fe7c7b76682e.png)

即在该评测任务被抓取后出现在顶端。

---

同时递交评测/运行自测也会出现同样的情况。不管在哪一个评测记录页，当有人提交代码后评测任务也会出现在顶端。

![image](https://user-images.githubusercontent.com/57275149/115645735-78d88180-a353-11eb-80c8-6739034d496b.png)

图中框出的是刚提交的评测。

**Comment by undefined-moe** [comment]
未出现在此页中的评测任务更新会被判定为新的提交，放在页面顶部显示
