### ISSUE TITLE
编译时系统错误

### ISSUE THREAD

**Issue by onlyLTY** [hydro-dev/Hydro#12]
编译时报系统错误
![屏幕截图 2020-10-29 185647](https://user-images.githubusercontent.com/46625336/97559596-9964f600-1a18-11eb-8f6b-e16626e9ec3a.png)

**Comment by undefined-moe** [comment]
请检查：

- 沙箱服务是否正常运行
- 是否正确配置了测试数据
- 是否安装了所需编译器
