### ISSUE TITLE
希望在一些页面上能够加宽 markdown 编辑器，或是减小编辑器内字体大小

### ISSUE THREAD

**Issue by Macesuted** [hydro-dev/Hydro#127]
在部分页面中由于编辑器过窄，用户体验还是比较差的，~~更别说分屏预览了~~。

![image](https://user-images.githubusercontent.com/57275149/116962653-28f5a500-acd9-11eb-9379-273b66ecf136.png)

**Comment by undefined-moe** [comment]
Hint: 
![image](https://user-images.githubusercontent.com/29992205/116990042-28730380-ad05-11eb-8015-90397123f7f8.png) 这里有个全屏按钮
