### ISSUE TITLE
上传图片时提示“please config: options.upload.url”

### ISSUE THREAD

**Issue by xiangyanhao** [hydro-dev/Hydro#130]
在账户设置中的“个人简介”栏中，上传图片时会提示“please config: options.upload.url”，但在题目编辑页面中则无此问题。

**Comment by undefined-moe** [comment]
暂时仅支持题目编辑中快捷上传图片。

**Comment by wuxianucw** [comment]
个人简介目前设计就是不支持上传图片的，可能相关按钮容易造成误解。

**Comment by undefined-moe** [comment]
由于 vditor 已不再推荐使用，将关闭该 issue。
