### ISSUE TITLE
题目名称前的通过状态与得分

### ISSUE THREAD

**Issue by Suiseiseki-2016** [hydro-dev/Hydro#132]
发现在更新后题目名称前多了一个数字，猜测为成绩。

然而根据显示其并不会变化：

如图：
![图片](https://user-images.githubusercontent.com/81913295/117236814-13f54f00-ae5c-11eb-94d4-31fa79fb01ad.png)
（Accepted 均为 100 分，Wrong Answer 为 80 分）

可能是一个 Bug？

**Comment by wuxianucw** [comment]
`psdoc` 对应的声明中没有 `score` 成员，因此全部 fallback 成 0 了，正在想办法修。

**Comment by Suiseiseki-2016** [comment]
貌似已经好了。

**Comment by Suiseiseki-2016** [comment]
诶不对，好像还有锅，这次更诡异了……

![图片](https://user-images.githubusercontent.com/81913295/117253219-8e809780-ae79-11eb-8455-679797d3b4a8.png)

然后这是这一题我的提交记录是这样：

![图片](https://user-images.githubusercontent.com/81913295/117253295-a8ba7580-ae79-11eb-97c9-f7b8c6af1399.png)

这是干脆记录直接弄错了吗？

**Comment by undefined-moe** [comment]
这是题目配置的问题，与系统无关。
