### ISSUE TITLE
关于评测的一些问题！

### ISSUE THREAD

**Issue by Suiseiseki-2016** [hydro-dev/Hydro#133]
Hydro 的比较器是不是有一些问题呢？

![图片](https://user-images.githubusercontent.com/81913295/117260365-96dcd080-ae81-11eb-9788-fb15150e829d.png)

这个的第 2,4 个点都 WA 了，然而实际上下载下来测试正确的！

这一题中的 ASCII 码是在 **34~254** 之间哦，比较器应当使用 **signed** char 类型实现的吧，这样的话是比较不了的。

比较器是不是应该改成 **unsgiend** char 类型呢，还是说这种情况下需要手写 SPJ 呢？

**Comment by wuxianucw** [comment]
https://github.com/hydro-dev/Hydro/blob/2d1522f671d9283ddc734e3bf6ed61d6b24b3a85/packages/hydrojudge/src/checkers.ts#L18-L61

不看代码就在猜什么 `signed` `unsigned`，咱能别云了吗（

**Comment by ReiAccept** [comment]
我觉得应该提供一下你出问题的数据吧==

**Comment by Suiseiseki-2016** [comment]
> 
> 
> 我觉得应该提供一下你出问题的数据吧==

testlib 似乎也不支持 unsigned char，另外，这就是 Hydro-BZOJ 上的 2176 啊，您可以直接去看，就是第二个点。

**Comment by Suiseiseki-2016** [comment]
> 
> 
> https://github.com/hydro-dev/Hydro/blob/2d1522f671d9283ddc734e3bf6ed61d6b24b3a85/packages/hydrojudge/src/checkers.ts#L18-L61
> 
> 不看代码就在猜什么 `signed` `unsigned`，咱能别云了吗（

非常抱歉，但是确实出了这个问题……

**Comment by Macesuted** [comment]
考虑加一下 spj 吧。

**Comment by wuxianucw** [comment]
用 Rust 也没过，大概确实有锅

**Comment by undefined-moe** [comment]
diff可能对于控制字符的判定比较迷 建议使用spj
