### ISSUE TITLE
重测 AC 提交前应该先让题目 nAccept - 1 ？

### ISSUE THREAD

**Issue by Macesuted** [hydro-dev/Hydro#136]
同一道题目反复重测一份 AC 代码可以让该题通过数不断上升，AC 率也可能超过 100%。

**Comment by undefined-moe** [comment]
存在的问题：

如何判断该提交计入了 nAccept？ （同一用户仅首次提交AC代码会计入 nAccept，重测之后的代码让 nAccept - 1 显然是不合适的）。

**Comment by undefined-moe** [comment]
若进行大规模重测，请考虑重测完成后重新运行 problemStat 脚本。

**Comment by BATTLEHAWK00** [comment]
> 存在的问题：
> 
> 如何判断该提交计入了 nAccept？ （同一用户仅首次提交AC代码会计入 nAccept，重测之后的代码让 nAccept - 1 显然是不合适的）。

考虑使用数据库聚合函数而不是开字段来统计？统计后可以把数据缓存起来

**Comment by undefined-moe** [comment]
> 考虑使用数据库聚合函数而不是开字段来统计？统计后可以把数据缓存起来

`aggregate` 会消耗大量资源，不可能在每次提交后触发。现有的 `problemStat` 脚本即基于 `aggregate` ，于每日凌晨三点运行并自动校正由重测导致的数据错误。正常情况下仅在每次评测完成后简单对字段加一即可。
