### ISSUE TITLE
能否在题目config.yaml内指定此题支持的语言

### ISSUE THREAD

**Issue by Macesuted** [hydro-dev/Hydro#139]
部分题目可能有需求禁止用户用部分语言进行提交（如特殊比赛，或是不允许用户使用 O2 之类的）。

可以从评测机返回 System Error 反馈本题不支持本语言，或是最好能够在用户提交的时候直接去除那些不能使用的语言。

且最好能够在题面上显示这些信息。

**Comment by undefined-moe** [comment]
config.yaml:

```yaml
langs:
  - pas
  - php
```
