### ISSUE TITLE
评测机的 ”judge_extra_files“ 配置无效？

### ISSUE THREAD

**Issue by Limorton** [hydro-dev/Hydro#154]
我按照官方配置对USACO的题目([链接](https://hydro.org.cn/d/limm/p/7))进行了如下的配置：
![image](https://user-images.githubusercontent.com/27600540/121171413-10a11900-c889-11eb-98c1-1297834124ab.png)
官方指导配置：
![image](https://user-images.githubusercontent.com/27600540/121171693-64136700-c889-11eb-99ac-1832af8445bf.png)

可是提交评测却发现只对了三个输出无解的测试点，其他依赖 `dict.txt`  的测试点均失效，该代码在 USACO 官网可以 AC，是不是配置 `judge_extra_files` 是无效的，文件并没有复制到评测机的工作目录？

评测记录链接：https://hydro.org.cn/d/limm/record/60bf4821c267a6f8bc236093

**Comment by undefined-moe** [comment]
`judge_extra_files` 中的文件仅会在比对过程中复制进工作目录（供自定义比较器使用），但这不会改变内置比较器的行为。在不使用 `Special Judge` 时配置 `judge_extra_files` 是毫无意义的。

**Comment by undefined-moe** [comment]
您可能需要正确配置 Special Judge。
