### ISSUE TITLE
评测机的 user_extra_files 和 judge_extra_files 配置实测均无效

### ISSUE THREAD

**Issue by Limorton** [hydro-dev/Hydro#155]
配置了两个数据，发现这两个配置实际上并没有将对应文件复制到评测时的工作目录。测试用题链接如下：

user_extra_files 配置测试用题：https://hydro.org.cn/d/limm/p/7

judge_extra_files 配置测试用题：https://hydro.org.cn/d/limm/p/8

**Comment by undefined-moe** [comment]
已更新云端评测机版本。似乎文件已经正确写入。

**Comment by Limorton** [comment]
user_extra_files配置已经正常，但 judge_extra_files 配置似乎还不行

**Comment by undefined-moe** [comment]
fixed by e6927bcc49aa465576f866472f9ea97b6dc425cb
