### ISSUE TITLE
开发计划

### ISSUE THREAD

**Issue by undefined-moe** [hydro-dev/Hydro#157]
已移至 [https://roadmap.hydro.ac/](https://roadmap.hydro.ac)

**Comment by youyu** [comment]
kindEditor，比较老了不考虑了，说实话功能挺全面的

**Comment by undefined-moe** [comment]
> kindEditor，比较老了不考虑了，说实话功能厅全面的

太丑了不考虑

**Comment by Kanna-Neko** [comment]
建议：比赛编辑题目之后题目排序困难，建议改成像uid一样，输入后有联想，但联想后不必出现方框固定住，无法修改顺序，只能删光后面的才能修改

**Comment by undefined-moe** [comment]
@wuxianucw feat: drag&drop

**Comment by wuxianucw** [comment]
> 建议：比赛编辑题目之后题目排序困难，建议改成像uid一样，输入后有联想，但联想后不必出现方框固定住，无法修改顺序，只能删光后面的才能修改

可以考虑增加插入功能和拖拽排序功能，由于比赛题目一般较少而且顺序应当是经仔细斟酌决定的，此 feature 仅具备 normal 优先级。

**Comment by youyu** [comment]
会不会支持，团队功能（或者班级功能）？即：域内分组

**Comment by undefined-moe** [comment]
PRs welcome

**Comment by youyu** [comment]
通过后看题解，官方站点还没正式上线吗？
