### ISSUE TITLE
操作系统支持问题

### ISSUE THREAD

**Issue by ghost** [hydro-dev/Hydro#159]
我在美国的vps想部署hydro，但是我试了debian、centos6、7、8、ubuntu20的服务器版本，都显示“不支持的操作系统”，请问如何解决

**Comment by undefined-moe** [comment]
支持ubuntu 2004 。请确认是否为原版镜像。
另 请提供 /etc/os-release 文件内容。

**Comment by ghost** [comment]
我比较习惯centos7是不是只能用开发者模式

**Comment by undefined-moe** [comment]
centos的系统内核非常古董，可能会带来安全问题，请升级后再操作。
请注意关闭selinux。
您可以参照安装脚本 (install/install.js) 中的代码进行手动部署（开发模式与生产模式均可）。
由于 yum 源版本较旧，您可能需要手动编译软件包。

**Comment by ghost** [comment]
我还是试一下ubuntu2004

**Comment by ghost** [comment]
root@sweet-pipe-1:~# wget https://s3.undefined.moe/public/install -O install && chmod +x install && ./install
--2021-06-24 06:01:04--  https://s3.undefined.moe/public/install
Resolving s3.undefined.moe (s3.undefined.moe)... 216.24.255.41
Connecting to s3.undefined.moe (s3.undefined.moe)|216.24.255.41|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8090629 (7.7M) [application/x-executable]
Saving to: ‘install’

install                                100%[============================================================================>]   7.72M  16.3MB/s    in 0.5s    

2021-06-24 06:01:07 (16.3 MB/s) - ‘install’ saved [8090629/8090629]

[jssh] 2021/06/24 06:01:07 开始运行 HydroOJ 安装工具 / Starting HydroOJ installation tool
[jssh] 2021/06/24 06:01:07 正在初始化安装 / Preparing
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 6060 (apt-get)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
[jssh] 2021/06/24 06:01:11 exec: exit status 100
[jssh] 2021/06/24 06:01:11 Error when running apt-get install -y curl wget gnupg
root@sweet-pipe-1:~# apt-get install -y curl wget gnupg
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 6060 (apt-get)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?


以上是ssh终端结果
果然可以使用ubuntu2004，但是又出问题了

**Comment by undefined-moe** [comment]
请关闭正在运行的其他apt进程。

**Comment by undefined-moe** [comment]
未收到更多信息，将关闭此 issue。
