### ISSUE TITLE
同一个域内用户分组

### ISSUE THREAD

**Issue by youyu** [hydro-dev/Hydro#160]
请问，同一个域内的用户支出分组不？

这样就可以共享题库，分组学习了

**Comment by Macesuted** [comment]
这里的分组是什么意思，需要什么功能？

**Comment by youyu** [comment]
> 这里的分组是什么意思，需要什么功能？

举个例子说明：加入学校里进行Python基础教学，一个老师可能带很多个班，一个老师可以建设一个域，但是没必要每个班建设一个域，然后按班级分组，每个组登录后，进入自己组的任务和作业

**Comment by youyu** [comment]
> 这里的分组是什么意思，需要什么功能？

举个例子说明：学校里进行Python基础教学，一个老师可能带很多个班，一个老师可以建设一个域，但是没必要每个班建设一个域，然后按班级分组，每个组登录后，进入自己组的任务和作业

**Comment by Macesuted** [comment]
该功能可通过域实现，为避免给用户的使用带来更多不必要的麻烦，还是建议您通过建设多个域来做到该功能。

如果是担心在多个域内多次传题目过于复杂，我们已经提供了跨域引用题目功能，可以帮助用户在多个域之间共享题目。您可以在每个域内为不同班创建任务和作业，同时借助该功能达到所有题目只创建一次的目的。

**Comment by undefined-moe** [comment]
提供了跨域共享题目的功能（仍在进行稳定性测试）
以下是使用样例：

1. 在主域 域设置 中，设置 `Share problem with` 为 `*` （允许任何域引用）
2. 在其他域中，创建比赛或作业，题目ID以 `system:1` 格式填写（后方数字为在主域中的题目编号）

提示：此功能仍在进行稳定性测试，可能含有bug，若您遇到欢迎反馈。

**Comment by undefined-moe** [comment]
另外，您也可尝试编写插件为比赛或作业添加邀请码。

**Comment by youyu** [comment]
谢谢大佬，指点明白了。这个支持WSL2.0 测试吧

**Comment by youyu** [comment]
> 提供了跨域共享题目的功能（仍在进行稳定性测试）
> 以下是使用样例：
> 
> 1. 在主域 域设置 中，设置 `Share problem with` 为 `*` （允许任何域引用）
> 2. 在其他域中，创建比赛或作业，题目ID以 `system:1` 格式填写（后方数字为在主域中的题目编号）
> 
> 提示：此功能仍在进行稳定性测试，可能含有bug，若您遇到欢迎反馈。
后续会开发域内，用户分组功能吗？

**Comment by undefined-moe** [comment]
现已支持在域内创建不同的权限组。但是在同一个域内使用不同的题目分配到不同的用户组是伪需求，无任何意义，完全可以使用多个域实现，因此此功能短期内不会考虑添加。

**Comment by youyu** [comment]
> 现已支持在域内创建不同的权限组。但是在同一个域内使用不同的题目分配到不同的用户组是伪需求，无任何意义，完全可以使用多个域实现，因此此功能短期内不会考虑添加。

其实信息技术分班日常教学中，还是用得到的，用HustOJ简单实现了，可用简单够用，实际使用中也还算方便。其实场景是不太一样的

**Comment by undefined-moe** [comment]
请详细说明如何进行分组，组间有何差异，用于何种应用场景

**Comment by youyu** [comment]
> 请详细说明如何进行分组，组间有何差异，用于何种应用场景
编程教学在学校普及推广阶段，课堂教学也在实践中，一个老师可以见一个自己的域，他会带10个左右的班级，每周的课每个班级的教学内容是一样的（就会有很多相同内容的重复竞赛），希望每个班都有他们专属的作业和竞赛，学生登录后选择竞赛、作业后只显示面向自己班级的内容，聚焦自己要学习的内容。
（现在学生有角色选项，班级可以通过角色来实现），竞赛和作业添加是：要有角色选项，把作业分配给对应的角色应该就可以实现了）

**Comment by undefined-moe** [comment]
我的建议如下：

- 将题目上传至 system 域，在 system 域内的 管理域->编辑域资料 中将 `Share problem with domain` 设置为 `*` ，保存
- 为所有班级单独创建域，并将不同班级的学生分配到不同的域，设置仅允许域内用户访问该域
- 在域内创建比赛/作业，题目列表填写 `system:1, system:2` 格式的题号（1，2为题目在主域的ID）

为什么不进行域内分组：

域内用户权限组对全域的资源均有效，一个资源隶属于某个特定域。而在域层面内再添加分组会导致四级权限结构，工程量过大，且会大幅增加系统上手难度（结构过于复杂），因此暂不考虑此功能。
