### ISSUE TITLE
docker安装Hydro无法启动

### ISSUE THREAD

**Issue by Rratic** [hydro-dev/Hydro#172]
帮别人发的
[链接](https://hydro.ac/discuss/610b35911aee7d91e637c9ab#1628124561381)

**Comment by undefined-moe** [comment]
说了114514遍除非你可以熟练配置docker容器且会基础的错误处理否则别用docker

**Comment by undefined-moe** [comment]
哪怕你 `docker run -it -v "/data:/data" --network host --privileged ubuntu` 再跑安装脚本都更稳
