### ISSUE TITLE
脚本无法使用

### ISSUE THREAD

**Issue by Kanna-Neko** [hydro-dev/Hydro#176]
在使用内置脚本“deleteUser”的时候，我填入了存在的用户4，但是系统报出了“Field {0} validation failed.”异常，且别的脚本统一是该错误，尝试不同方式开启服务，都无法使用脚本。

**Comment by undefined-moe** [comment]
所有脚本均有且仅有一个 JSON 参数。其格式请参照项目 `packages/hydrooj/src/scripts/` 下对应文件内的定义。
同时请注意：该删除账户功能仅为适应 GDPR 的设计，它不会真正删除账户，而是抹去账户的所有信息，但仍然保留账户用于占位。
更建议您封禁账户而不是删除账户。
