### ISSUE TITLE
希望客观题题面允许markdown

### ISSUE THREAD

**Issue by Rratic** [hydro-dev/Hydro#179]
我现在使用`-desc: "内容"`勉强能在单行用（我怀疑这能正确显示是个bug）

**Comment by Rratic** [comment]
现在加引号方式也挂了

**Comment by Rratic** [comment]
我有一个想法：可以考虑使用特殊的3引号，语言为`objective-编号`和`objective-input-编号`（没有为填空）
例如
```objective
$题目$
```

```objective-c
A. foo
B. bar
3. bla
```
同时暂时兼容旧方式

@undefined-moe

**Comment by undefined-moe** [comment]
1. 为 markdown 引入新的解析语法可能更加 confusing.
2. 会在客观题以外的 markdown 部分中产生副作用。
3. 请学习如何正确使用 yaml 换行
4. 如果有更好的解决方案， **PRs Welcome**

**Comment by Rratic** [comment]
@undefined-moe 

重要的是客观题会有latex啊，怎么写都会挂

> 会在客观题以外的 markdown 部分中产生副作用

正常人不会去写objective-n，检测一下type就行

**Comment by undefined-moe** [comment]
**PRs Welcome**

**Comment by Rratic** [comment]
**想法**（光速逃

**Comment by Rratic** [comment]
算了，要是看得懂代码我还是试试

**Comment by Rratic** [comment]
markdown部分在哪里啊qwq

**Comment by Rratic** [comment]
```json
"dependencies": {
    "esbuild": "^0.12.18",
    "js-yaml": "^4.1.0",
    "jsesc": "^3.0.2",
    "katex": "^0.13.13",
    "lodash": "^4.17.21",
    "markdown-it": "^12.2.0",
```
\*\*

**Comment by Rratic** [comment]
@undefined-moe 对不起，但是这一部分是dependency给的

**Comment by Rratic** [comment]
我现在打算允许嵌入一个（弱化的）lua
