### ISSUE TITLE
vjudge出问题了

### ISSUE THREAD

**Issue by hello8693** [hydro-dev/Hydro#180]
为什么我的remotejudge域只有一道题啊
![37DC6523CF8819E8641A400B31039C6F](https://user-images.githubusercontent.com/88492699/130065756-5488218c-93dc-4073-b345-102c009a1b0e.jpg)
提交还显示没有测试点，SE
文档里的设置我都做了
OJ也重启了

**Comment by Macesuted** [comment]
麻烦多提供点信息，有链接的话请给出链接

**Comment by hello8693** [comment]
http://1.117.142.235/d/codeforces/p
这是vjudge域的链接
![image](https://user-images.githubusercontent.com/88492699/130066558-00a535f8-fba9-4277-a656-a7de94d3f1fa.png)
题库里就这么一道题
然后提交显示：
![image](https://user-images.githubusercontent.com/88492699/130066635-3b9b550f-b60a-4e91-a42e-d1e8a47c0e8b.png)

**Comment by hello8693** [comment]
我是一键脚本安装的

**Comment by Macesuted** [comment]
给一下 hydrooj 的 log。

**Comment by hello8693** [comment]
怎么看log啊（linux小白）

**Comment by Macesuted** [comment]
```sh
pm2 log hydrooj
```

**Comment by hello8693** [comment]
[TAILING] Tailing last 15 lines for [hydrooj] process (change the value with --lines option)
/root/.pm2/logs/hydrooj-error.log last 15 lines:
3|hydrooj  |   resource: '/hydro',
3|hydrooj  |   requestid: '169CB070D85B9BC6',
3|hydrooj  |   hostid: 'c312e575-cd17-462b-b071-bd464df90c98',
3|hydrooj  |   amzRequestid: null,
3|hydrooj  |   amzId2: null,
3|hydrooj  |   amzBucketRegion: null
3|hydrooj  | }
3|hydrooj  |
3|hydrooj  |   Error: write EPIPE
3|hydrooj  |       at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
3|hydrooj  |
3|hydrooj  |
3|hydrooj  |   Error: read ECONNRESET
3|hydrooj  |       at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
3|hydrooj  |

/root/.pm2/logs/hydrooj-out.log last 15 lines:
3|hydrooj  | [I]  vjudge  codeforces/tv-zhu-oj-remotejudge: logged in
3|hydrooj  | [I]  judge  Submission: codeforces/611e452944e22ffb583d95ca { pid: '1' }
3|hydrooj  | [E]  judge  Error: Problem data not found.
3|hydrooj  |         at cacheOpen (/usr/local/share/.config/yarn/global/node_modules/@hydrooj/hydrojudge/src/service.ts:96:13)
3|hydrooj  |         at async JudgeTask.submission (/usr/local/share/.config/yarn/global/node_modules/@hydrooj/hydrojudge/src/service.ts:245:21)
3|hydrooj  |         at async JudgeTask.handle (/usr/local/share/.config/yarn/global/node_modules/@hydrooj/hydrojudge/src/service.ts:209:11)
3|hydrooj  |         at async Consumer.consume (/usr/local/share/.config/yarn/global/node_modules/hydrooj/src/model/task.ts:81:11)
3|hydrooj  | [I]  judge  End: status=8 score=0 time=0ms memory=0kb
3|hydrooj  | [I]  judge  Submission: codeforces/611e452944e22ffb583d95ca { pid: '1' }
3|hydrooj  | [E]  judge  Error: Problem data not found.
3|hydrooj  |         at cacheOpen (/usr/local/share/.config/yarn/global/node_modules/@hydrooj/hydrojudge/src/service.ts:96:13)
3|hydrooj  |         at async JudgeTask.submission (/usr/local/share/.config/yarn/global/node_modules/@hydrooj/hydrojudge/src/service.ts:245:21)
3|hydrooj  |         at async JudgeTask.handle (/usr/local/share/.config/yarn/global/node_modules/@hydrooj/hydrojudge/src/service.ts:209:11)
3|hydrooj  |         at async Consumer.consume (/usr/local/share/.config/yarn/global/node_modules/hydrooj/src/model/task.ts:81:11)
3|hydrooj  | [I]  judge  End: status=8 score=0 time=0ms memory=0kb

**Comment by Macesuted** [comment]
运行

```sh
pm2 log hydrooj --lines=1000 | grep vjudge
```

**Comment by hello8693** [comment]
3|hydrooj  |     at async Service.sync (/usr/local/share/.config/yarn/global/node_modules/@hydrooj/vjudge/src/model.ts:87:13)
3|hydrooj  |     at async Service.main (/usr/local/share/.config/yarn/global/node_modules/@hydrooj/vjudge/src/model.ts:117:9) {
3|hydrooj  | [I]  loader  [ '/usr/local/share/.config/yarn/global/node_modules/hydrooj', '/usr/local/share/.config/yarn/global/node_modules/@hydrooj/ui-default', '/usr/local/share/.config/yarn/global/node_modules/@hydrooj/hydrojudge', '/usr/local/share/.config/yarn/global/node_modules/@hydrooj/import-qduoj', '/usr/local/share/.config/yarn/global/node_modules/@hydrooj/login-with-github', '/root/addon', '/usr/local/share/.config/yarn/global/node_modules/@hydrooj/vjudge' ]
3|hydrooj  | [I]  common  Model init: /usr/local/share/.config/yarn/global/node_modules/@hydrooj/vjudge +570ms
3|hydrooj  | [I]  vjudge  codeforces/tv-zhu-oj-remotejudge: logged in
3|hydrooj  | [I]  vjudge  codeforces: Syncing page 1
3|hydrooj  |         at async Service.sync (/usr/local/share/.config/yarn/global/node_modules/@hydrooj/vjudge/src/model.ts:87:13)
3|hydrooj  |         at async Service.main (/usr/local/share/.config/yarn/global/node_modules/@hydrooj/vjudge/src/model.ts:117:9) Promise {
3|hydrooj  |       at async Service.sync (/usr/local/share/.config/yarn/global/node_modules/@hydrooj/vjudge/src/model.ts:87:13)
3|hydrooj  |       at async Service.main (/usr/local/share/.config/yarn/global/node_modules/@hydrooj/vjudge/src/model.ts:117:9) {
3|hydrooj  | [I]  vjudge  codeforces/tv-zhu-oj-remotejudge: logged in

**Comment by hello8693** [comment]
显示这个，然后就不动了

**Comment by hello8693** [comment]
显示这个，然后就不动了

**Comment by Macesuted** [comment]
> 显示这个，然后就不动了

这是正常，直接 ctrl+c 退出即可。

**Comment by hello8693** [comment]
关键是这到1000行吗
@Macesuted

**Comment by wuxianucw** [comment]
> 关键是这到1000行吗

`grep` 仅显示相关行

**Comment by Macesuted** [comment]
奇怪，能不能给个临时服务器登录方式，或者等一下 undefined。

**Comment by hello8693** [comment]
怎么弄啊

**Comment by hello8693** [comment]
怎么整临时登录方式

**Comment by hello8693** [comment]
还是让undefined弄吧
我不会临时登录

**Comment by undefined-moe** [comment]
1. 请确保您有稳定的 Internet 连接。
2. 请确保您的 ip 未被 Codeforces 禁止访问。
3. 请正确重启整个实例而非单个工作线程。
4. 请尽可能不要在数据同步过程中重载服务器。
