### ISSUE TITLE
题面嵌入html失败

### ISSUE THREAD

**Issue by Rratic** [hydro-dev/Hydro#181]
> 支持内嵌 HTML：（用来对付部分 Markdown 搞不定的东西）

我试了一下，无效，本来想用js处理的

**Comment by undefined-moe** [comment]
建议您学习网络安全入门知识。

**Comment by Rratic** [comment]
那为什么要写文档里呢？！

**Comment by undefined-moe** [comment]
支持HTML不代表支持JavaScript。

**Comment by Rratic** [comment]
可以考虑在加载前弄个按钮”信任该作者并允许js“之类的

**Comment by Rratic** [comment]
讲真，html想卡也能卡死

**Comment by undefined-moe** [comment]
这边建议直接将按钮改名为 “信任作者并允许作者访问我账户的密码，登录位置，使用设备等敏感信息” 更为合理。

**Comment by Rratic** [comment]
完全可以。。。

不行的话加上允许预览代码

**Comment by undefined-moe** [comment]
建议您先向 Luogu/Vijos 等允许任意用户上传题目的 OJ 提议该功能。
