### ISSUE TITLE
关于题面嵌入弱化lua的事宜

### ISSUE THREAD

**Issue by Rratic** [hydro-dev/Hydro#182]
表达式树的代码写了一半了
现在我来征求一些意见
1. 直接解释好还是转成js好？
2. 我准备提供2个接口，`getval(element_id)`和`setval(element_id,value)`访问html元素的`value`，您觉得可以吗
3. 安全原因，协程、模块导入肯定不能要，请问循环次数、函数递归是否有必要进行限制？

**Comment by Rratic** [comment]
@undefined-moe

**Comment by wuxianucw** [comment]
请不要把简单问题复杂化。

**Comment by Rratic** [comment]
？

**Comment by Rratic** [comment]
由于markdown的3引号部分是在dependecy部分，无法进行增添，而undefined认为js不安全
允许嵌入脚本可以进行演示、也可以提供局部答题框

**Comment by wuxianucw** [comment]
markdown 的语法可以通过挂载插件增强，详见 markdown-it 文档。

**Comment by Rratic** [comment]
emmm
> 可以进行演示

**Comment by wuxianucw** [comment]
这同样可以使用插件来实现，此功能不在主仓库开发计划内，请考虑自行编写插件实现。

**Comment by Rratic** [comment]
~~我回来了~~
> 此功能不在主仓库开发计划内，请考虑自行编写插件实现。

packages/ui-default/backendlib/markdown-it-xss.js不是在本地吗，我就给它做个扩展

**Comment by wuxianucw** [comment]
在主仓库内不代表在主仓库开发计划内，炫技请单开插件 repo。经审核通过后，您的插件将被列在文档的社区插件中。

**Comment by Rratic** [comment]
markdown-it 文档在哪？

**Comment by Rratic** [comment]
github page无法访问 淦

**Comment by wuxianucw** [comment]
若需要更多帮助，建议移步 Discussions。
