### ISSUE TITLE
vjudge插件无法加载，其他插件都成功加载

### ISSUE THREAD

**Issue by guke1024** [hydro-dev/Hydro#195]
开发者您好，我按照步骤正确地安装了vjudge插件，但是无法加载，并且日志中也没有任何vjudge的日志，只有一个loader的消息，其他插件则全都能正常运行。这两天也进行过以下尝试：①删除所有插件，仅安装vjudge插件，vjudge无法加载且没有日志；②安装全部插件，除vjudge外其余插件都能正常运行，vjudge无法加载且没有日志；③安装部分插件，同样也是以上情况；④删除codeforces域，删除vjudge数据库以及相关组件，重新安装vjudge，同以上情况。这应该怎样解决。

**Comment by undefined-moe** [comment]
请确认 loader 是否尝试加载了 vjudge 插件。
插件安装后需要使用 `hydrooj addon add <pluginId>` 添加到插件列表。

**Comment by BATTLEHAWK00** [comment]
![8%L$ `8)95OHGA7U8ZB{YGE](https://user-images.githubusercontent.com/45313304/132315743-bdfff653-295a-4fd8-a9a2-ccd4df0343a2.png)
如图，我们是按照文档上的步骤做的，也用命令行add上去了，addon.json文件有vjudge插件，日志上显示loader加载列表中有vjudge插件，但插件本身没有任何日志输出，也不会自动同步题目，其它插件运作是正常的

**Comment by BATTLEHAWK00** [comment]
![8%L$ `8)95OHGA7U8ZB{YGE](https://user-images.githubusercontent.com/45313304/132315743-bdfff653-295a-4fd8-a9a2-ccd4df0343a2.png)
如图，我们是按照文档上的步骤做的，也用命令行add上去了，addon.json文件有vjudge插件，日志上显示loader加载列表中有vjudge插件，但插件本身没有任何日志输出，也不会自动同步题目，其它插件运作是正常的
