### ISSUE TITLE
求助MongoDB

### ISSUE THREAD

**Issue by ELEVENStudio-Main** [hydro-dev/Hydro#197]
在使用安装脚本安装并注册账号后，使用`hydrooj cli user serSuperAdmin xxx`以及其他命令时，都提醒"codeName:NamespaceNotFound"，如何解决？

**Comment by ELEVENStudio-Main** [comment]
@Macesuted ?

**Comment by ELEVENStudio-Main** [comment]
@undefined-moe

**Comment by ELEVENStudio-Main** [comment]
MongoError: ns does not exist: hydro.record

**Comment by undefined-moe** [comment]
应当已于 2.34.4 修复该问题。
请更新到最新版本后再次尝试。

**Comment by ELEVENStudio-Main** [comment]
是最近一小时刚部署的，是最新版本。
可能是因为之前部署过部分Hydro。
建议添加删除脚本。

**Comment by undefined-moe** [comment]
新版本是十分钟前刚发的 🤣

**Comment by ELEVENStudio-Main** [comment]
哦好的😅
