### ISSUE TITLE
有一个关于测试数据的疑问

### ISSUE THREAD

**Issue by ELEVENStudio-Main** [hydro-dev/Hydro#200]
为什么HydroOJ识别不到大数据？（指文件大小）

**Comment by undefined-moe** [comment]
测试数据基于文件名识别，与文件大小无关。
详情请参照文档相关内容。

**Comment by ELEVENStudio-Main** [comment]
但是我从LibreOJ导入的 贪吃蛇 的 snake20.in 等数据，共计20个，但评测时只显示六个是为甚么呢

**Comment by ELEVENStudio-Main** [comment]
![](https://z3.ax1x.com/2021/09/13/4F9fnH.png)
![](https://z3.ax1x.com/2021/09/13/4F9hBd.png)

**Comment by undefined-moe** [comment]
测试数据的导入是在题目创建后后台进行的。导入后请等待一段时间再提交。立刻提交会出现测试数据未完全导入的情况。

**Comment by ELEVENStudio-Main** [comment]
好的，解决了，谢谢🙏
