### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by ELEVENStudio-Main** [hydro-dev/Hydro#201]
Ideas from 学校OJ
1. 在控制面板添加对网站服务端的硬件资源占用情况的抓取。
2. 在控制面板显示流量统计（提交量、通过量）
3. 计算活跃用户，显示在首页
 --------

4. 用户页面的Tab切换动画好像跑出去了
5. 能不能把讨论的"Hydro"换成自定义OJ名？
6. 题库顶部的搜索框和列表在一起不显眼，建议放在旁边
7. 在题库页面顶部也添加页数切换
8. 添加"Star"功能标记题目
9. 站内消息好像还不能实时刷新会话？

**Comment by ELEVENStudio-Main** [comment]
不然评测机卡死了还要登录服务器控制台来看是不是硬件原因

**Comment by BATTLEHAWK00** [comment]
正在做。。（新建文件夹

**Comment by ELEVENStudio-Main** [comment]
@BATTLEHAWK00 建议哪些能过

**Comment by undefined-moe** [comment]
1. 系统状态页面有简易的信息
2. 评测记录列表下方有数据统计
3. 何为活跃用户？
4. known issue
5. 改数据库
6. 放哪都有人会找不着
7. 可以做
8. 可以做
9. Hydro 不是 IM 工具，没有必要自动更新

**Comment by ELEVENStudio-Main** [comment]
1. 好吧
2. 我的意思是图表更直观，一定程度地反映了OJ的受欢迎程度
3. 最近七天登录三次以上的用户
9. 好吧

**Comment by BATTLEHAWK00** [comment]
@ELEVENStudio-Main Prometheus插件已经发布了 自己配置prometheus和grafana实现监控面板    
https://github.com/BATTLEHAWK00/hydro-prom-exporter
