### ISSUE TITLE
建议：添加维护暂停使用功能

### ISSUE THREAD

**Issue by ELEVENStudio-Main** [hydro-dev/Hydro#209]
描述：启用维护模式后除了管理员和超级管理员之外的所有用户访问oj任意界面都会显示暂停使用。

**Comment by undefined-moe** [comment]
欢迎自己做。

**Comment by Macesuted** [comment]
麻烦不要再发 issue 了，你所提到的大部分建议都是你的个人需求而非我们所需要添加的功能。

Hydro 提供收费的功能定制服务，如果你真的有需要麻烦和 undefined 联系而不是在这里发 issue。
