### ISSUE TITLE
用C#提交代码出现错误

### ISSUE THREAD

**Issue by MasterYuan418** [hydro-dev/Hydro#215]
使用其他语言提交均不会有错误，唯独使用C#会发生错误。
  报告：`execve: start: no such file or directory`
  
![图片](https://user-images.githubusercontent.com/58651976/134003974-42175eb8-f459-48ed-b5ac-07c8894f7093.png)
### 环境信息
Ubuntu 20.04LTS on VMWare 16 Pro
HydroOJ 2.36.8
使用脚本安装
**物理机信息**
Windows 10 build 19043
AMD R5 3600 + DDR4 16GB

**Comment by undefined-moe** [comment]
安装脚本只会帮您安装 g++。
若需要请手动安装 C# 编译器后重启 hydro-sandbox 。

**Comment by MasterYuan418** [comment]
@undefined-moe 非常感谢，问题已经解决，劳烦你了。
