### ISSUE TITLE
请问如何给用户tag?

### ISSUE THREAD

**Issue by MasterYuan418** [hydro-dev/Hydro#218]
rt
  非常感谢。
  MasterYuan

**Comment by Macesuted** [comment]
请参阅文档 <https://hydro.js.org/docs/system/FAQ/#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%94%A8%E6%88%B7%E6%A0%87%E7%AD%BE>

**Comment by MasterYuan418** [comment]
非常感谢，已解决问题。
