### ISSUE TITLE
导入syzoj-ng的题目无法获取数据，无法批量导入

### ISSUE THREAD

**Issue by zryoung** [hydro-dev/Hydro#221]
如题

**Comment by undefined-moe** [comment]
请参照文档检查minio是否设置正确

**Comment by pt3155420267** [comment]
最近也出现了syzoj测试数据无法正常导入。。。，题面是可以导入的，就是测试数据总是进不来，minio已设置正确

**Comment by undefined-moe** [comment]
经测试，syzoj-ng 的导入功能完全正常。
请注意：`https://files.loj.ac/libreoj-data/` 从国内访问十分缓慢，可能会经常出现下载出错的情况。

**Comment by pt3155420267** [comment]
感谢回答，那如果下载出错的话，怎么能批量重新下载。。难道真的要把题目删了重新导入吗？

**Comment by undefined-moe** [comment]
网络问题不在考虑范围内。请尝试使用 proxychains4 等工具。

**Comment by pt3155420267** [comment]
如果测试数据一直没导入上去，会一直重试吗？还是在次数超过几次后就不会再获取了

**Comment by undefined-moe** [comment]
目前不会进行重试。
