### ISSUE TITLE
题目是文件IO还是标准IO，能否根据需要改变

### ISSUE THREAD

**Issue by zryoung** [hydro-dev/Hydro#224]
如题，如果平时练习，就可以用标准IO，如果开比赛，可以设置相应的题目在比赛环境下用文件IO

**Comment by undefined-moe** [comment]
短期内可能不会考虑实现。

**Comment by undefined-moe** [comment]
可在比赛外使用特殊设定的提交语言来将文件IO题转换为标准IO。

使用形如

```bash
/bin/bash -c "cat *.in | ./code >`ls | grep '.in' | cut -d . -f1`.out"
```

的方式运行选手程序。

（仅作实现思路提示，上述语法可能有误）

**Comment by undefined-moe** [comment]
现在会在测评时传入环境变量 `HYDRO_CONTEST` 。可在 `execute.sh` 中自行按需完成重定向操作。
