### ISSUE TITLE
Contests 'Show Filter' is broken

### ISSUE THREAD

**Issue by RLukas2** [hydro-dev/Hydro#234]
Sorry for not using Chinese because Chinese isn't my mother tongue. Also this is my first time using Github, I don't know how to pull request as my friend said so I only know use this Issues tab.

So contest filter will be broken if you do this:
- Go to 'Contest' tab.
- Choose option from 'All' to any other option that is available (IOI, OI, or ACM/ICPC) contests.
- Switch back to show 'All'. And it'll direct you to the Error page (https://hydro.ac/contest?rule=0).

So as I read the HTML for 'Contest' tab, I see that "All" is using value="0", but when I delete the definition of value it works flawlessly without Error. I think it could be value="0" isn't defined in the rule. So the guard caught it and give you an error.
So previous errored code in contest_main.html - Line 64: `<option value="0" selected="">All</option>`
New fixed code in contest_main.html - Line 64: `<option value selected="">All</option>`

**Comment by undefined-moe** [comment]
Thanks for pointing that out!

**Comment by undefined-moe** [comment]
To create a pull request for a simple change, you can find and open the file you want to edit, then click the edit icon on the right. Then follow the instructions. It's easy. 😄  

![image](https://user-images.githubusercontent.com/29992205/137434790-e2a963e7-859e-4a84-9967-299638479cbf.png)
