### ISSUE TITLE
建议加一个文件上传功能（不是下载）

### ISSUE THREAD

**Issue by sky390** [hydro-dev/Hydro#242]
建议加一个文件上传功能（不是下载），配合 PDF 插件会方便一些，单纯的我的文件只能下载。

**Comment by undefined-moe** [comment]
我没有理解这是个啥

**Comment by sky390** [comment]
![image](https://user-images.githubusercontent.com/69176684/139446127-920f03f5-444d-49a4-aa57-9d016f1d8a42.png)
上传我的文件会自动下载

**Comment by undefined-moe** [comment]
@wuxianucw 你pdfjs也炸了

**Comment by undefined-moe** [comment]
可以尝试将文件上传至题目的附加文件后在题目中使用 `file://filename` 引入。

**Comment by sky390** [comment]
谢谢，我试试

**Comment by sky390** [comment]
![image](https://user-images.githubusercontent.com/69176684/139446863-b5f05e1d-4763-45f5-9916-b9770e9a8ad3.png)
![image](https://user-images.githubusercontent.com/69176684/139446897-5f8f3447-9ad9-4d3e-8fa8-bebfe68a2b7d.png)
![image](https://user-images.githubusercontent.com/69176684/139446925-3536309a-1254-4bda-b04f-0f5ff0de29c3.png)
怎么还是不行啊？

**Comment by wuxianucw** [comment]
> ![image](https://user-images.githubusercontent.com/69176684/139446863-b5f05e1d-4763-45f5-9916-b9770e9a8ad3.png) ![image](https://user-images.githubusercontent.com/69176684/139446897-5f8f3447-9ad9-4d3e-8fa8-bebfe68a2b7d.png) ![image](https://user-images.githubusercontent.com/69176684/139446925-3536309a-1254-4bda-b04f-0f5ff0de29c3.png) 怎么还是不行啊？

能否提供链接以供测试

**Comment by sky390** [comment]
怎么提供啊

**Comment by sky390** [comment]
好像是因为idm的原因

**Comment by sky390** [comment]
OK
