### ISSUE TITLE
一点个人建议

### ISSUE THREAD

**Issue by qazwsxtem** [hydro-dev/Hydro#245]
1. bug：个人主页 - 题解被赞 数值无论如何都是 0
2. 建议 仍像 Vijos 一样在个人主页显示“讨论”“贡献”“递交”标签页
3. 建议 有把各题目讨论区集中在一起查看的地方（单个题目讨论区几乎不可能被及时看到，这就失去了设置题目讨论区的意义）
4. 建议 取消训练加入后才能查看题目的限制和要求
5. 文件上传貌似没有大小限制？可能应该限制一下？
6. 考虑一下把默认内存改成 512 M？（雾
7. 还是希望具有 博客 以及 比赛rating 功能

**Comment by undefined-moe** [comment]
对于2，我也不知道有啥意义。
对于3，你可以直接查看讨论总版。
对于4，我也不知道为啥要这么干。
对于5，是有限制的。
对于7，比赛一直是参与rp计算的。

**Comment by qazwsxtem** [comment]
> 
> 
> 对于2，我也不知道有啥意义。 对于3，你可以直接查看讨论总版。 对于4，我也不知道为啥要这么干。 对于5，是有限制的。 对于7，比赛一直是参与rp计算的。

仅个人观点
2,：显示一些自己的痕迹对用户可能更友好？对自己来说，可能会方便查看以前的问题/想法（而非通过站内通知或翻看讨论版）；对别人来说，某用户的讨论/题解若质量较高，可能具有参考价值；也并非会使社区氛围变差。
4：题目可以作为训练质量的参考，而非一定要点参与再具体了解。
7：如果要更好地体现用户真实水平，唯比赛的 rating 可能比综合的 rp 优秀一些？

**Comment by undefined-moe** [comment]
关于2：我个人非常不喜欢把内容和特定的人关联起来这一行为。
关于7：从设计理念上来说它就不是用来评价用户水平的。
