### ISSUE TITLE
bug: Rating Calc Failed

### ISSUE THREAD

**Issue by ELEVENStudio-Main** [hydro-dev/Hydro#247]
版本: Hydro v3.1.27     
db.user无任何操作    
![截屏2021-11-10 下午1.15.22.png](https://img-kysic-1258722770.file.myqcloud.com/e7292bcd1d490e7a41ad682dc1f2bc25/e84c1fcc2ea44.png)

**Comment by undefined-moe** [comment]
无法复现。这可能是您删除过用户导致的。

**Comment by ELEVENStudio-Main** [comment]
请问有workaround吗

**Comment by undefined-moe** [comment]
检查 domain.user 表中所涉及到的 uids 是否均在 user 表中存在；
检查 domain.user 表中涉及到的 domainIds 是否均在 domain 表中存在。

**Comment by ELEVENStudio-Main** [comment]
fixed.
