### ISSUE TITLE
请问为什么没有在仓库中包括 `yarn.lock`

### ISSUE THREAD

**Issue by Zxilly** [hydro-dev/Hydro#248]
注意到
https://github.com/hydro-dev/Hydro/blob/5cae54ed0a09236ba98e2094335db15ab3074bc5/.gitignore#L27
然后 `tsconfig.json` 是运行时动态生成的，请问为什么采取这样的设计呢？不锁定依赖版本可能带来意外的 bug

**Comment by undefined-moe** [comment]
在遵从semver的情况下，lock不是必需品。
lock会频繁增删，同时大量触发各种ci的dep check，显然没有必要。
