### ISSUE TITLE
Multi mail send error

### ISSUE THREAD

**Issue by pandadtdyy** [hydro-dev/Hydro#249]
Hydro发送复合型（带text和html）的邮件时发送报错

发送报错：Can't send mail - all recipients were rejected: 454 Transient reject by behaviour spam at Rcpt State(Connection IP address:x.x.x.x)ANTISPAM_BAT[01201311R8168S153012151f, ay29a033002195083]: too frequently sending

查询邮件服务商文档发现是被拦截
猜测因text内容过于简短直接被邮件服务商判断为spam阻止
本地去掉text仅发送html内容邮件则发送成功
邮件服务商：阿里企业邮

**Comment by undefined-moe** [comment]
不同服务商限制不同，Hydro没有必要也无法针对各个服务商作出优化。  
请尝试使用专用于验证码发送的服务商或是参照文档自行修改邮件模板。  
Too frequently sending 通常的解决方案有且只有更换服务商。

**Comment by pandadtdyy** [comment]
> 不同服务商限制不同，Hydro没有必要也无法针对各个服务商作出优化。 请尝试使用专用于验证码发送的服务商或是参照文档自行修改邮件模板。 Too frequently sending 通常的解决方案有且只有更换服务商。

只是不理解在可以只发送html邮件的情况下为什么还要发送text，且邮件的text基本无用，用户实际查看也是查看html

**Comment by undefined-moe** [comment]
据我所知这只是普普通通的 limit exceeded 了而已。显然 limit 是按照 IP 来的。你拿到本地发当然就没问题了

**Comment by pandadtdyy** [comment]
我这边是通过同一服务器发送的 
通过注释了mail.ts发送时的text修改发信内容而发送成功
附两封邮件前后区别
我的认为是阿里的spam因为part1的text拦下了邮件 附两封邮件的邮件原文截图
fail mail 通过更换邮件商完成发送
![fail mail](https://user-images.githubusercontent.com/15662967/141648906-bc9075f3-6498-49a6-99e8-1a421c2ef9ed.png)
![success mail](https://user-images.githubusercontent.com/15662967/141648911-d9c6f3ab-eb5c-4bfc-b098-1aff57a0f762.png)

**Comment by undefined-moe** [comment]
还是建议您根据需要自行改动。
既然有服务商会拦截有text部分的邮件，那为什么就不会有服务商拦截text部分为空的邮件呢

**Comment by pandadtdyy** [comment]
我这边测试后发现只是因为text内容过于简单而被拦截，目前已单独fork进行改动
