### ISSUE TITLE
Code editor for submission

### ISSUE THREAD

**Issue by junukwon7** [hydro-dev/Hydro#25]
How about adding a code editor at the submission page? Not just textbox.
Maybe things like this?
https://github.com/kazzkiq/CodeFlask

**Comment by undefined-moe** [comment]
You can just use "Open Scratchpad (Alt+E)" at problem detail page. this is based on monaco editor.

**Comment by junukwon7** [comment]
> You can just use "Open Scratchpad (Alt+E)" at problem detail page. this is based on monaco editor.

oh I got it 👍
