### ISSUE TITLE
关于提交答案题

### ISSUE THREAD

**Issue by Minion123456** [hydro-dev/Hydro#250]
1.请问提交答案题支持 SPJ 吗？
2.我将提交答案题的数据上传时没有问题，但上传 config.yaml 时出现了如下提示：
Cannot create property 'langs' on string 'Cannot parse: outputs config not found'
我的 config.yaml 如下：
type: submit_answer

checker_type: lemon
checker: spj.cc

score: 10
cases:
  - input: 1.in
    output: 1.ans
  - input: 2.in
    output: 2.ans
  - input: 3.in
    output: 3.ans
  - input: 4.in
    output: 4.ans
  - input: 5.in
    output: 5.ans
  - input: 6.in
    output: 6.ans
  - input: 7.in
    output: 7.ans
  - input: 8.in
    output: 8.ans
  - input: 9.in
    output: 9.ans
  - input: 10.in
    output: 10.ans

**Comment by sparrowhe** [comment]
提交答案题用outputs数组定义答案，所以我觉得你得用正常题目模式才可以用spj

**Comment by undefined-moe** [comment]
目前的提交答案题按行给分。

```yaml
type: submit_answer
outputs:
- [行1答案, 分值]
- [行2答案, 分值]
```

**Comment by Minion123456** [comment]
所以现在提交答案题支持 SPJ 吗？

**Comment by sparrowhe** [comment]
> 所以现在提交答案题支持 SPJ 吗？

并不，参见 #168

**Comment by Minion123456** [comment]
建议支持一下 SPJ

**Comment by Minion123456** [comment]
顺便修改一下这个：
https://hydro.js.org/docs/user/testdata
