### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by t8y2** [hydro-dev/Hydro#252]
希望能在个人主页显示自己做过的题号

**Comment by undefined-moe** [comment]
这有什么用吗

**Comment by youyukyc** [comment]
1、便于膜拜大佬，追寻大佬脚步，跟着做题
2、便于老师查看学生做题情况
3、有些细节还是可以参考HustOJ，的确在目前来看更实用

**Comment by undefined-moe** [comment]
8d7a4460665340aeaff3949f01aad5d066d1dc0a 已实现
