### ISSUE TITLE
建议：‘我的文件’里暂存的文件，可以直接关联浏览器的下载器

### ISSUE THREAD

**Issue by youyu** [hydro-dev/Hydro#253]
我的文件，可以方便用来，暂存训练代码的，但是单击只会转到“复制到剪贴板”，而Chrome浏览器的下载还没有国产的那种新建下载功能，使用体验不是一般的难受。

**Comment by youyu** [comment]
按“Ctrl+Click”也是一样的效果，不是自动下载的

**Comment by undefined-moe** [comment]
右键，在新标签页中打开链接

**Comment by youyukyc** [comment]
测试可用，谢谢指点
