### ISSUE TITLE
bug: 在已登录的情况下仍会触发 FireFox 的密码自动填充功能

### ISSUE THREAD

**Issue by Tiphereth-A** [hydro-dev/Hydro#257]
在 FireFox 设置了主密码且已登录 Hydro 账号的情况下, 进入任一界面均会触发 FireFox 的输入主密码的弹窗

![1](https://user-images.githubusercontent.com/62847935/143591505-09f5e25a-37fa-43b7-b26b-02bdf0b8f3f5.png)

![2](https://user-images.githubusercontent.com/62847935/143591598-de3e4683-17f4-4b79-b08f-afc54d25e0ac.png)

![3](https://user-images.githubusercontent.com/62847935/143591641-b34afa26-ab40-4c0a-afab-007df0c4c8d4.png)

FireFox 版本: 94.0.2 Windows 64-bit

**Comment by undefined-moe** [comment]
7cdd542ed1c5636004b72a04a8ad186855587a0f 可能解决了该问题。
另，如果一个不显示的 `input` 就能触发自动补全 我觉得这是 firefox 自己的问题。

**Comment by Tiphereth-A** [comment]
> [7cdd542](https://github.com/hydro-dev/Hydro/commit/7cdd542ed1c5636004b72a04a8ad186855587a0f) 可能解决了该问题。 另，如果一个不显示的 `input` 就能触发自动补全 我觉得这是 firefox 自己的问题。

已解决
