### ISSUE TITLE
bug: 执行hydrooj命令报告"/usr/bin/env: ‘node’: No such file or directory"

### ISSUE THREAD

**Issue by MasterYuan418** [hydro-dev/Hydro#266]
![图片](https://user-images.githubusercontent.com/58651976/145700554-366ccfe6-8313-48e1-a28c-243b14d3c7a5.png)
如图所示，使用一键安装脚本进行安装。执行hydrooj命令立刻报告找不到node。

### 环境
`
CPU: Intel(R) Xeon(R) Platinum 8361HC CPU @ 2.60GHz`
`RAM: 4GB`
`系统：Ubuntu 20.04LTS
`

**Comment by wuxianucw** [comment]
请切换到 root 用户再尝试执行。
