### ISSUE TITLE
【求助】关于vjudge的一点求助

### ISSUE THREAD

**Issue by Kanna-Neko** [hydro-dev/Hydro#267]
作为hydro的使用者，我想添加一个关于luogu的vjudge供团队使用，但在观察文档和源码后，和codeforces域相同的lang的配置一项并不知道要填写什么，请求作者能不能发一下配置❤️❤️

**Comment by undefined-moe** [comment]
洛谷 RemoteJudge 服务是由上海洛谷网络科技有限公司提供的收费功能。

**Comment by Kanna-Neko** [comment]
thanks！
