### ISSUE TITLE
Cannot find module ./ko_KR.js

### ISSUE THREAD

**Issue by junukwon7** [hydro-dev/Hydro#27]
More work to be done?
I removed and re-added ui-default and got this error. The site, translation seems clear but all scripts don't work.

![image](https://user-images.githubusercontent.com/48399106/100417610-a3841e00-30c4-11eb-8782-3f77ddadd1f0.png)

![image](https://user-images.githubusercontent.com/48399106/100417646-bac30b80-30c4-11eb-9bfa-874115cde1bf.png)

![image](https://user-images.githubusercontent.com/48399106/100417816-0d042c80-30c5-11eb-8f9a-2810334e92b8.png)

**Comment by undefined-moe** [comment]
you should upgrade to the latest version 2.13.58.
(timeago.js only provides ko.js, not ko_KR.js, so the timeago_locale have to be set correctly.)

**Comment by junukwon7** [comment]
> you should upgrade to the latest version 2.13.58.
> (timeago.js only provides ko.js, not ko_KR.js, so the timeago_locale have to be set correctly.)

Oh it was a typo. Thanks for fixing it.
