### ISSUE TITLE
[Help] Get error "Please also install @hydrooj/ui-default"

### ISSUE THREAD

**Issue by riverstore** [hydro-dev/Hydro#273]
Hi, first I'd like to say thanks for the great work.

I follow this guidence 

[开发环境部署](https://hydro.js.org/dev/#%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96)

But when I start the project by this command `yarn debug --port=2333` I get message

`Please also install @hydrooj/ui-default`

And while access to `http://localhost:2333/` I get this json string (without the UI)

>{
>  "contents": [
>    [
>      "contest",
>      [],
>      {}
>    ],
>    [
>      "homework",
>      [],
>      {}
>    ],
>    [
>      "training",
>      [],
>      {}
>    ],
>    [
>      "discussion",
>      [],
>      {}
>    ]
>  ],
>  "udict": {},
>  "domain": {
>    "_id": "system",
>    "lower": "system",
>    "owner": 1,
>    "name": "Hydro",
>    "bulletin": "Welcome to Hydro!",
>    "roles": {
>      "root": "-1"
>    },
>    "avatar": ""
>  },
>  "vnodes": [],
>  "pdocs": [],
>  "psdict": {}
>}

I'm new to typescript, I google for serveral days but can't found good infos.

Please help me. 

Thanks a lot.

Regard.

**Comment by undefined-moe** [comment]
for development mode, you can use 

```sh
npx hydrooj addon add @hydrooj/ui-default # with npx
# or
node packages/hydrooj/bin/hydrooj.js addon add @hydrooj/ui-default # without npx
```

to enable it.

for `npx` tool installation, run `yarn global add npx` **outside** the project directory.

**Comment by undefined-moe** [comment]
@Macesuted @wuxianucw 请更新文档相关部分

**Comment by riverstore** [comment]
It work for me now.

Thanks a lot :)
