### ISSUE TITLE
[bug] virtual judge codeforces 运行返回结果产生问题

### ISSUE THREAD

**Issue by Kanna-Neko** [hydro-dev/Hydro#276]
若这道题ac，则会一直保持running状态，会继续测试其他题目。
若wa则正常。
测试结果表明主站也有此问题。
主站指的是官方站点的codeforces域

**Comment by jaxleof** [comment]
主站指的是官方站点的codeforces域

**Comment by undefined-moe** [comment]
Codeforces 现在会返回 `Happy New Year!` 而非 `Accepted` 。  
请耐心等待圣诞节结束。

![image](https://user-images.githubusercontent.com/29992205/147385977-88c8ad11-215b-4deb-96ab-917774a854c3.png)
