### ISSUE TITLE
[Help] Using "hydrojudge" on WSL2

### ISSUE THREAD

**Issue by riverstore** [hydro-dev/Hydro#278]
Hi,

Sorry to make a new issue again. By following your suggestion , I launch Hydro UI on Windows 10 and HydroJudge on WSL2. Now I have 2 more questions ^^

**1.** I follow this docs [hydrojudge](https://hydro.js.org/plugins/hydrojudge/#%E4%BD%9C%E4%B8%BA%E9%99%84%E5%8A%A0%E7%BB%84%E4%BB%B6) but this link [此处](https://hydro.js.org/docs/cli/#%E5%88%9B%E5%BB%BA%E8%AF%84%E6%B5%8B%E8%B4%A6%E5%8F%B7) is dead

> 首先需要创建一个有 PRIV_JUDGE 权限的账户，具体方法参照 此处。（在部署 Hydro 的服务器上运行）(vj4 用户需参照 vj4 的方法 创建账户）

Can you please fix this link.

And, if I use this method, which value I should fill to `sandbox_host` field on System setting?

**2.** When trying to run go-judge on WSL2, I can access it from Windows 10 host via this url `http://localhost:5050`. But when I try to submit a solution, I get this error message (The value of `sandbox_host` field is `http://localhost:5050`)

>Compile Error 0ms 0KiB
>Sandbox Error
>"connect ECONNREFUSED 127.0.0.1:5050"

Look like that `localhost` is transformed to `127.0.0.1`. When trying to connect to `http:://127.0.0.1:5050` I get this message

>Unable to connect

I think, if the URL still keep as `localhost` I can use WLS2 for judging.

Please help me.

Thank a lot.

Regard.

**Comment by undefined-moe** [comment]
@Macesuted 链接挂了

Account management instructions here:
https://hydro.js.org/docs/system/cli/#%E5%91%BD%E4%BB%A4%E5%88%97%E8%A1%A8

For dedicated judge daemon, just fill the config in judge.yaml

E.g.

```yaml
hosts:
  <hosts configuration here...>
sandbox_host: http://localhost:5050/
```

**Comment by criyle** [comment]
At the same time, the `hydrojudge` need to be ran within the same file system as go-judge to access test files, so setting up a standalone `hydrojudge` within the same WSL2 distribution should work fine by following this guide. https://hydro.js.org/plugins/hydrojudge/#作为独立进程

**Comment by riverstore** [comment]
Thank a lot for you quick help as usually. By following your help I can judge with go-judge on WSL2 now. But I found that, if I click `Submit Solution (F10)` repeatedly too fast, I will get `System Error ` message, and here is the error log

> Found 20 testcases.
> Sandbox Error
> Error: Sandbox Error
>     at run (g:\Code\OJ system\Hydro\Hydro\packages\hydrojudge\src\sandbox.ts:142:15)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at compile (g:\Code\OJ system\Hydro\Hydro\packages\hydrojudge\src\compile.ts:16:13)
>     at async Promise.all (index 0)
>     at Object.judge (g:\Code\OJ system\Hydro\Hydro\packages\hydrojudge\src\judge\default.ts:145:34)
>     at JudgeTask.submission (g:\Code\OJ system\Hydro\Hydro\packages\hydrojudge\src\service.ts:224:13)
>     at JudgeTask.handle (g:\Code\OJ system\Hydro\Hydro\packages\hydrojudge\src\service.ts:186:17)
>     at Consumer.consume (g:\Code\OJ system\Hydro\Hydro\packages\hydrooj\src\model\task.ts:47:21)

This not happend when run go-judge and Hydro on the same PC.

Can you please check.

Thank a lot.

Regard.

**Comment by riverstore** [comment]
And here is more infos from cmd

> [E]  judge  Error: Sandbox Error
>         at run (g:\Code\OJ system\Hydro\Hydro\packages\hydrojudge\src\sandbox.ts:142:15)
>         at runMicrotasks (<anonymous>)
>         at processTicksAndRejections (node:internal/process/task_queues:96:5)
>         at compile (g:\Code\OJ system\Hydro\Hydro\packages\hydrojudge\src\compile.ts:16:13)
>         at async Promise.all (index 0)
>         at Object.judge (g:\Code\OJ system\Hydro\Hydro\packages\hydrojudge\src\judge\default.ts:145:34)
>         at JudgeTask.submission (g:\Code\OJ system\Hydro\Hydro\packages\hydrojudge\src\service.ts:224:13)
>         at JudgeTask.handle (g:\Code\OJ system\Hydro\Hydro\packages\hydrojudge\src\service.ts:186:17)
>         at Consumer.consume (g:\Code\OJ system\Hydro\Hydro\packages\hydrooj\src\model\task.ts:47:21)
> [D]  judge  Next: 0 { message: { message: 'Sandbox Error', params: 'connect ECONNREFUSED 127.0.0.1:5050', stack: 'Error: Sandbox Error\n' + '    at run (g:\\Code\\OJ system\\Hydro\\Hydro\\packages\\hydrojudge\\src\\sandbox.ts:142:15)\n' + '    at runMicrotasks (<anonymous>)\n' + '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' + '    at compile (g:\\Code\\OJ system\\Hydro\\Hydro\\packages\\hydrojudge\\src\\compile.ts:16:13)\n' + '    at async Promise.all (index 0)\n' + '    at Object.judge (g:\\Code\\OJ system\\Hydro\\Hydro\\packages\\hydrojudge\\src\\judge\\default.ts:145:34)\n' + '    at JudgeTask.submission (g:\\Code\\OJ system\\Hydro\\Hydro\\packages\\hydrojudge\\src\\service.ts:224:13)\n' + '    at JudgeTask.handle (g:\\Code\\OJ system\\Hydro\\Hydro\\packages\\hydrojudge\\src\\service.ts:186:17)\n' + '    at Consumer.consume (g:\\Code\\OJ system\\Hydro\\Hydro\\packages\\hydrooj\\src\\model\\task.ts:47:21)' } }

Regard.

**Comment by undefined-moe** [comment]
did you disabled built-in judge daemon in system settings (?

**Comment by riverstore** [comment]
> did you disabled built-in judge daemon in system settings (?

Thank a lot. I disable the built-in judge daemon and it work fine now.

Edit: Can you please add this to [here](https://hydro.js.org/plugins/hydrojudge/#%E4%BD%9C%E4%B8%BA%E7%8B%AC%E7%AB%8B%E8%BF%9B%E7%A8%8B) ^^

Thanks again ^^.

Regard.
