### ISSUE TITLE
[Feature Request] 希望提供隐藏成绩表和统计信息的IOI赛制

### ISSUE THREAD

**Issue by AutumnKite** [hydro-dev/Hydro#281]
如题，标准的IOI赛制应只能看到自己的提交结果。

**Comment by undefined-moe** [comment]
看起来目前的各大平台的 IOI 赛制都可以互相看榜（？

**Comment by AutumnKite** [comment]
LOJ/SYZOJ 的 IOI 赛制应该看不了榜，而且诸如集训队互测、CTT、PKUWC、APIO 等比赛的 IOI 赛制都是看不了榜的，希望还是能出一个能否看榜的选项

**Comment by undefined-moe** [comment]
您可以尝试自行加载一个插件进行 patch 操作。

`model.ts`

```ts
Hydro.model.contest.RULES.ioi.showScoreboard = (tdoc, now) => now > tdoc.endAt;
```

**Comment by AutumnKite** [comment]
是需要自己编写一个插件吗

**Comment by undefined-moe** [comment]
大概是参照 https://hydro.js.org/docs/system/frontend-modify/ 说明，创建 /root/addon/model.ts 写入上述内容

**Comment by AutumnKite** [comment]
好的，谢谢

**Comment by pandadtdyy** [comment]
已通过 IOI(Strict) 赛制实现，同时该赛制支持每道题的排行榜得分为用户每个子任务在所有提交中的最大得分的和。
