### ISSUE TITLE
vjudge最近是不是挂了，还是说就我有问题

### ISSUE THREAD

**Issue by Kanna-Neko** [hydro-dev/Hydro#292]
### Discussed in https://github.com/hydro-dev/Hydro/discussions/290

<div type='discussions-op-text'>

<sup>Originally posted by **jaxleof** January 12, 2022</sup>
cf vjudge最近挂了，询问询问看看大家的情况</div>

**Comment by undefined-moe** [comment]
CF 加入了反爬虫逻辑。  
目前已知的是：该模块可以使用，但需要以一些其他的方式使用。  
建议阅读相关源码。

**Comment by Kanna-Neko** [comment]
难过

**Comment by Kanna-Neko** [comment]
[new question]我观察发现，之前提到的Forbidden问题是由于无法自动登录产生的，解决此问题后正常使用了一段时间，但在某次更新后产生了一个新的问题，“Cannot read property 'length' of undefined”

**Comment by undefined-moe** [comment]
无法复现。
