### ISSUE TITLE
[Bug Report] 可忽略的bug

### ISSUE THREAD

**Issue by Kanna-Neko** [hydro-dev/Hydro#303]
虽然可忽略，但还是要发出来

在域资料编辑中添加单行<div>会造成侧边框下移至页面底端

**Comment by undefined-moe** [comment]
无法复现这个问题。

**Comment by Kanna-Neko** [comment]
添加单行《div》
单破折号打不出来

**Comment by Kanna-Neko** [comment]
<div>

**Comment by Kanna-Neko** [comment]
< div >

**Comment by Kanna-Neko** [comment]
修改一下，是域公告

**Comment by undefined-moe** [comment]
这个问题暂时无法被修复。对于 Markdown 和 HTML 混用的情况，检查 HTML 标签的完整性并正确转义不匹配的标签难以实现。

**Comment by Rratic** [comment]
或许可考虑警告并删除不完整的标签
~~尽管确实可忽略，虽然有加&lt;b&gt;会影响侧边栏等奇怪效果~~

**Comment by Kanna-Neko** [comment]
应作为低优先级bug记录，或许哪年bug都修完了可以回来看看。
如果要修改该问题，个人认为可以尝试从前端布局入手，比如将浮动改成grid布局，或许能解决问题

**Comment by undefined-moe** [comment]
这是由于tag不完全导致的。用户输入的标签没有正确闭合，破坏了后续页面的正确结构。这个问题仅能通过过滤用户输入的方式处理。
