### ISSUE TITLE
关于julia的TLE问题

### ISSUE THREAD

**Issue by Rratic** [hydro-dev/Hydro#306]
```cpp
#include <iostream>
using namespace std;
#define ll long long
#define ull unsigned long long
int main(){
    ios::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
    cout<<0;
    return 0;
}
// Accepted 1.734053ms 384KiB
```
```jl
print(0)

# Accepted 486.353756ms 90872KiB

for i in 1:10
    print(i,' ')
end

# Accepted 609.955319ms 94200KiB
# Accepted 565.325099ms 94200KiB
```
由于当前的评测和计时模式，有以下解决方案
1. 调整评测和计时模式：评测时创建.jl计时文件调用Benchmark测时
2. 增加常数时间600ms，常数空间90000KiB，可考虑在部分比赛中禁用

**Comment by undefined-moe** [comment]
没有必要为单个语言开后门。

**Comment by Rratic** [comment]
> https://discourse.juliacn.com/t/topic/5972

**Comment by undefined-moe** [comment]
给 julia 开了两倍时限。空间限制没救了。

**Comment by Rratic** [comment]
~~问题不是k而是b啊喂~~；空间限制可能确实不严重

---

方案1是否完全不可行？

**Comment by undefined-moe** [comment]
方案 1 完全可行。但是为了这 1% 的语言降低代码的可维护性是非常不值得的。

**Comment by Rratic** [comment]
~~找了一圈未发现相关信息~~ 以记录k的相同/相似方式记录b是否可行、安全且不会降低代码的可维护性？

* `y=kx+b`

**Comment by undefined-moe** [comment]
我无法理解。

**Comment by Rratic** [comment]
1. 两倍时限在技术上是如何实现的？

**Comment by undefined-moe** [comment]
直接设置时间限制为两倍。

**Comment by Rratic** [comment]
我无法理解。

---

能否以相同方式将时间限制增加600ms？

**Comment by undefined-moe** [comment]
不同环境下启动需要的时间也不同。这么做是毫无意义的。

**Comment by Rratic** [comment]
1. 那么是否可以允许管理员在一定范围内配置相关数据
2. 是否可以在hydro安装时进行测试并保留数据（否）

**Comment by undefined-moe** [comment]
那我可以告诉你目前 97% 以上的 Hydro 实例都没有配置 julia 语言。你觉得这样做有意义吗？

**Comment by Rratic** [comment]
> 在一定范围内配置相关数据

适用于任何语言

**Comment by undefined-moe** [comment]
我实在是想不出来除了 julia 还有多少语言需要这种东西了。

- cpp 和 c 选手会缺那启动的 1ms 吗？
- python 和 js 选手缺那启动的 20ms 吗？
- 就算是 Java 也仅需要约 90ms 就能正常启动。

同时，根据数据统计，Hydro 目前的 20 万提交中，仅有 44 条使用 Julia。换句话说，在 Hydro 目前超过 6K 的注册用户中，最多也仅有 44 人使用 Julia。给 1% 的用户补一个看似有用的功能是一个十分迷惑的行为。

Hydro 设计初衷是算法竞赛平台，而不是 Julia 教学平台。Julia 极高的基础占用本就不在主线需要考虑的范围内。
