### ISSUE TITLE
关于域内小组的疑问

### ISSUE THREAD

**Issue by youyu** [hydro-dev/Hydro#307]
1、因为一个人可以在多个小组，默认小组如何设置？小组之间如何切换？
2、题单能不能提供同一小组同学的做题结果反馈，跟作业一样？

**Comment by undefined-moe** [comment]
1. 我不知道这是在干什么。
2. 不能。

**Comment by youyu** [comment]
> 1. 我不知道这是在干什么。
> 2. 不能。

1、由于一个人可以有多个小组，教练给学员布置作业时，按小组布置的话，会方便些。这时候是给哪个小组？
2、由于作业不方便复制，如果题单有按小组反馈的效果，可以节省教练布置作业，检查作业的工作量。【如果也有多个小组，也需要切换小组】

**Comment by undefined-moe** [comment]
1. 给任意一个包含该用户的小组复制均可。
2. 不能。
