### ISSUE TITLE
[Feature Request] 增加控制面板中的导航功能及一些其它 feat 😀

### ISSUE THREAD

**Issue by Dynesshely** [hydro-dev/Hydro#308]
# 现有状况
1. 控制面板->系统设置: 内容较多
2. 控制面板->系统设置: 可设置项较少
3. 题面->Markdown编辑器->嵌入HTML: 支持的HTML标签过少

# 建议的改进
1. 侧栏增加目录导航，使用锚定快速跳转 / 或者 / 顶部增加导航栏，多Tab分页设计 （后一种工程量更多）
2. 提供一些配置文件的本机存放目录，方便管理员修改
3. 建议在控制面板->系统设置添加设置允许的 HTML 标签的面板

> 以上只是个人的一些愚见，还望多多指教。🪅
> 另外，本人建站之后希望进行一些魔改，但是是通过自动安装脚本进行的安装，不知从何下手，还望指教，感谢

**Comment by undefined-moe** [comment]
1. 本来右边是有导航面板的。然后它挂了。
2. 所有选项都在数据库的system表。
3. 我不知道还有哪些标签应该放行但没有放行。
4. 文档有插件系统的说明。关于事件钩子的使用可以在repo全局搜索 `bus.on` 和 `bus.emit` 等函数的调用。

**Comment by Dynesshely** [comment]
对于最后的关于魔改的一条请忽略，这一点在官方文档上介绍的很清楚<br>
是我的问题，打扰了 😅

**Comment by Dynesshely** [comment]
> 1. 本来右边是有导航面板的。然后它挂了。
> 2. 所有选项都在数据库的system表。
> 3. 我不知道还有哪些标签应该放行但没有放行。
> 4. 文档有插件系统的说明。关于事件钩子的使用可以在repo全局搜索 `bus.on` 和 `bus.emit` 等函数的调用。

感谢，关于第三点，最可见的是 <style> 标签没有放行

**Comment by undefined-moe** [comment]
style 可能严重干扰页面的正常显示，显然不应该放行

**Comment by Dynesshely** [comment]
那是否可以允许管理员在系统设置中进行设置来插入一些 css
方便管理员在一些地方进行一些更加个性化的设置

关于干扰页面显示的问题，我想这就是管理员的责任了，管理员有责任让自己的 css 不与默认的冲突

**Comment by undefined-moe** [comment]
footer_extra_html里可以插入style。也可以通过修改模板的方式注入样式，也可以使用ui插件（addon/public/foo.page.js)

**Comment by Dynesshely** [comment]
好的，感谢 😉
我想，这个 issue 可以关闭了
期待系统设置的导航面板能尽快修改
预祝 Hydro OJ 越来越好
