### ISSUE TITLE
[Bug report] 锁定主题 帖子所有者判断失效

### ISSUE THREAD

**Issue by 1107439216** [hydro-dev/Hydro#309]
好像判断写假了，现在谁都可以锁定主题，甚至是不属于自己的帖子，比如 [这个帖子](https://hydro.ac/discuss/616bf84297a67d9bf8d62f83) 就处于被我锁定的状态。

**Comment by undefined-moe** [comment]
看起来没写假 只是有个管理员不小心把这个权限放下去了。

**Comment by undefined-moe** [comment]
哦是我的问题 🤔
