### ISSUE TITLE
Test case validation limits

### ISSUE THREAD

**Issue by junukwon7** [hydro-dev/Hydro#31]
How about bringing the time, memory limits to the front-end page so the admin can change it?
Many Olympiad problems(like IOI or CEOI) contain much more.
https://github.com/hydro-dev/Hydro/blob/55352ab27bfcf2725838eae2c310ab4ce9e368e8/packages/hydrojudge/src/cases.ts#L286-L293

**Comment by undefined-moe** [comment]
this was designed as some people create a problem with hundreds of testcases and judging for a single code takes about an hour. (https://vijos.org/d/_MMD_/records/5f9cc894f413621b7b3571db)

I'll think about it. but hydrojudge is a package seperates from hydrooj, which makes it possible to deploy multiple judge client.  
that means judge cannot read configurations in database directly. (maybe by passing arguments when start?)  

--total_time_limit=120s (like this?)

**Comment by junukwon7** [comment]
> this was designed as some people create a problem with hundreds of testcases and judging for a single code takes about an hour. (https://vijos.org/d/_MMD_/records/5f9cc894f413621b7b3571db)
> 
> I'll think about it. but hydrojudge is a package seperates from hydrooj, which makes it possible to deploy multiple judge client.
> that means judge cannot read configurations in database directly. (maybe by passing arguments when start?)
> 
> --total_time_limit=120s (like this?)

Good. I was lost for more than 10 minutes finding what's wrong 😆

**Comment by undefined-moe** [comment]
please confirm whether the latest version works.

**Comment by undefined-moe** [comment]
@all-contributors please add @junukwon7 for ideas

**Comment by junukwon7** [comment]
> please confirm whether the latest version works.

Works fine! thx
