### ISSUE TITLE
求助：题库编辑模式多选操作失败

### ISSUE THREAD

**Issue by Dynesshely** [hydro-dev/Hydro#310]
# 前景情况
1. 有开启 CDN ，但推测不是 CDN 的问题，因为通过IP而不是域名的直接访问也有这种情况
2. 服务器状态良好
3. Hydro OJ 通过自动安装脚本安装，mongodb 以及其他环境均保留在本机
4. 尚未对 Hydro OJ 进行魔改，一切操作均在 WEB UI 面板中进行
5. 仅更改了个性化设置，其它设置项未修改
6. 已经正常运行至少一周，此Issue发布四小时前出现此问题

# 问题描述
1. 在题库中进行多选操作时，没有响应，但是刷新页面可以看到操作生效，但仅有选中的题目集合的第一题生效，其余无变化，例如取消隐藏，只有选中的题目的第一题会正常取消隐藏，而其余不会
2. 创建题目页面(包括编辑题目页面)，填写好相关信息后，点击创建(更新)后，浏览器显示无法访问页面，此时地址栏内容为：<domain>/problem/create

**Comment by undefined-moe** [comment]
盲猜：请卸载sonic插件

**Comment by Dynesshely** [comment]
卧槽，太强了，亲测有用<br>
牛逼 😀
