### ISSUE TITLE
[Bug Report] problem_edit : veditor will paste img url to lowercase

### ISSUE THREAD

**Issue by pandadtdyy** [hydro-dev/Hydro#316]
![image](https://user-images.githubusercontent.com/15662967/157943896-5ce10229-2c02-4c9c-b3a4-226b70d890d5.png)

通过`monaco`自动上传的图片会用`nanoid`进行重命名，但`veditor`会默认（？）将url的大写字母转为小写 造成图片404

**Comment by undefined-moe** [comment]
url 资源本身就应该是大小写敏感的。这是 vditor 的问题

**Comment by undefined-moe** [comment]
但是我觉得 vditor 应该不会搞出这种事情？是不是其他哪边搞出问题了

**Comment by pandadtdyy** [comment]
> 但是我觉得 vditor 应该不会搞出这种事情？是不是其他哪边搞出问题了

我在官网DEMO没复现 所以才提的issue 目前还没定位哪里出的问题

**Comment by pandadtdyy** [comment]
found bug: `$(img).src` 读取的出的地址是全小写的 jquery罪大恶极
![image](https://user-images.githubusercontent.com/15662967/158012562-b486ff5f-8880-4367-b1a8-032f0079573f.png)
