### ISSUE TITLE
建议完善的评测记录的过滤细节

### ISSUE THREAD

**Issue by canty007** [hydro-dev/Hydro#321]
1.“状态”的条件仅针对结果当前页有效，单击下一页后，该条件就失效。
![image](https://user-images.githubusercontent.com/21113894/159101733-8c453808-5c31-444e-b9ac-e53c72c0c9b4.png)

2.过滤结果的底部，建议有页码显示，“下一页“不是很直观，不能预估到评测结果。
![image](https://user-images.githubusercontent.com/21113894/159101833-e2cd56b3-fb65-4461-a632-3dc49a1e3ce2.png)

3.一道题的提面打开后，期待右侧有“评测记录”的查看按钮，能直接跳转到本题的评测记录过滤查询结果。
![image](https://user-images.githubusercontent.com/21113894/159101870-cac01140-f543-45f2-a3b7-1433ee215b7e.png)

**Comment by undefined-moe** [comment]
1. 是bug，待会修
2. 这个设计是为了防止在提交记录过多的时候避开全表扫描，优化性能
3. 题目标签上的【递交】和【通过】标签都是可以点的。
