### ISSUE TITLE
[Feature Request]能否将主页的 ranking 强制一下高度

### ISSUE THREAD

**Issue by dhclient** [hydro-dev/Hydro#322]
RT

有的个人主页上来就放了一张图片，而在主页的 ranking 上很长，看着很不爽

**Comment by undefined-moe** [comment]
在 `Windows10, Edge99` 环境是正常的。请提供相关有问题的环境信息。

**Comment by Baymin-ty** [comment]
在 `MacOS, Chrome 99` 环境同样正常。
