### ISSUE TITLE
评测记录的查询结果问题

### ISSUE THREAD

**Issue by canty007** [hydro-dev/Hydro#324]
域管理员，查询相应题目的评测记录，仅显示一页，没有“下一页”，无法查询到本题的所有评测情况。
建议增加“下一页”的链接。

**Comment by canty007** [comment]
已搞定，把32768的权限开了就行。打扰。

**Comment by Dynesshely** [comment]
> 已搞定，把32768的权限开了就行。打扰。

请记得及时关闭Issue
