### ISSUE TITLE
[Bug Report] 切换主题时出现 `Forward Loop Detect`

### ISSUE THREAD

**Issue by Dynesshely** [hydro-dev/Hydro#327]
来回切换主题时随机出现:  
![image](https://user-images.githubusercontent.com/50760269/159916820-1443ccdb-468f-474c-ba2f-71589ea6a816.png)

出现此状况后, 概率性刷新生效(刷新几次看运气), 去掉路由直接访问主站发现切换主题是生效的

本站情况: 一键安装脚本安装, 有使用 CDN, 携带头部转发, 完全回源

**Comment by undefined-moe** [comment]
请仅缓存 `js, css, woff, ttf, png, jpeg` 等资源。

**Comment by Dynesshely** [comment]
目前完全无缓存也有这种问题嘛

**Comment by Dynesshely** [comment]
所有文件目前设置为全部回源的

**Comment by undefined-moe** [comment]
如果 hydro.ac 无法复现那就一定是你的配置错了。  
SetTheme 路由的行为为重定向至 Referrer 或是 '/'。不应出现循环跳转问题。

**Comment by Dynesshely** [comment]
好的, 我尝试使用 ip 访问进行复现

**Comment by Dynesshely** [comment]
绕开CDN的配置问题

**Comment by Dynesshely** [comment]
emmm, 如此看来应该是CDN的问题

使用 IP 访问确实无法复现, 请教: CDN 应配置 301 跳转还是 302 跳转

**Comment by undefined-moe** [comment]
我也不知道 没用过

**Comment by Dynesshely** [comment]
好的, 感谢
