### ISSUE TITLE
Python编译器和运行时错误能不能给出更多信息？

### ISSUE THREAD

**Issue by maopucheng** [hydro-dev/Hydro#331]
Python的编译出错信息比较详细。
但是如果是runtime错误，譬如列表下标溢出之类就没有了。
能不能给出更多的runtime信息？
或者源码里哪里可以改？谢谢。

**Comment by undefined-moe** [comment]
hydro.ac 现已全站实装本功能，但默认关闭，您可以通过在题目 `config.yaml` 在 `user_extra_files` 设置项中传入一个空的 `enable_trace` 或是 `enable_python_trace` 文件来启用，详见文档 【测试数据格式 > 使用配置文件】 部分。  
如您需要自己实现，可以参照 [此题目](https://hydro.ac/d/system_test/p/11) 自定义评测流程。

友情提示：用户可以通过可以构造一个 Error 来骗取你的测试数据。使用前请务必三思。

**Comment by maopucheng** [comment]
谢谢，好的，我去试试，多谢了。
