### ISSUE TITLE
[Feature Request]希望可以在主站的记录中查到自己的所有提交

### ISSUE THREAD

**Issue by dhclient** [hydro-dev/Hydro#332]
rt,这对训练很有帮助

**Comment by Macesuted** [comment]
影响域之间独立性吧。

会有什么帮助么？

**Comment by dhclient** [comment]
> 影响域之间独立性吧。
> 
> 会有什么帮助么？

所有官方域的题都可以直接在主题库查看了，这难道不是更影响独立性吗? /qd

**Comment by dhclient** [comment]
我想直接在主题库查看我的所有提交

**Comment by dhclient** [comment]
如果可以的话

**Comment by pandadtdyy** [comment]
主题库也是一个单独的域 只是作为了默认显示

**Comment by dhclient** [comment]
而且个人主页也支持查看各个官方域的AC Problem了

**Comment by dhclient** [comment]
> 主题库也是一个单独的域 只是作为了默认显示

我没太明白您想表达的意思 /yiw

**Comment by undefined-moe** [comment]
你可以选择从题目点进你的提交记录。
