### ISSUE TITLE
是否有合并普通在线考试的题库系统的可能性？

### ISSUE THREAD

**Issue by maopucheng** [hydro-dev/Hydro#333]
先说下背景，我是少儿编程教师，不是针对信息奥赛训练的。

平时学生的练习，除了写代码（这部分可以用OJ），更多是使用了传统手段，譬如：选择题，判断题等客观题。平时，我们考察学生的学业水平，也是主要是纸面为主。这应该是我们国家，目前绝大部分普通的学校或者机构的实际情况。

鉴于此，我在寻找一个适合的开源系统，我找了很多开源的系统后发现，要么专做OJ的，要么专做在线考试题库的，没有合并这两项功能的开源系统。我尝试了QDUOJ，DMOJ，HUSTOJ，NOJ等一系列OJ，发现您实现的这个系统是目前最优秀的。

那你是否考虑在目前基础上，开发一点客观题题库的功能，不需要很复杂，简单实用即可。那么这样可以实现在同一个系统中既有客观题又有带OJ的编程题，解决了大部分普通的编程教育者痛点。

另外，从市场前景来说，相对于信奥这个细分的分支，普通的编程教育要广阔很多，天花板可能不是一个数量级的。

个人一点浅见，要是说错了，请别见笑，感谢您开发的系统。 :-P

**Comment by pandadtdyy** [comment]
https://hydro.js.org/docs/user/problem/#%E5%88%9B%E5%BB%BA%E9%A2%98%E7%9B%AE 请认真阅读文档后再提交issue

**Comment by undefined-moe** [comment]
完全可以实现，Hydro 目前也支持了对于单选题与填空题的简单判题支持。（详见 [文档](https://hydro.js.org/docs/user/problem/#%E9%A2%98%E9%9D%A2-2) ）  

但是目前来说仍存在以下问题：

1. 人手不够
2. 人手不够
3. 人手不够

鉴于以上的三个问题以及 Hydro 系统本身的定位，客观题的支持并不会作为高优先级目标进行集中优化。 ~~得加钱~~

**Comment by maopucheng** [comment]
嗯嗯，收到，我发邮件给您了。谢谢：）

**Comment by undefined-moe** [comment]
Closed for inactivity.
