### ISSUE TITLE
Stop judging if wrong?

### ISSUE THREAD

**Issue by junukwon7** [hydro-dev/Hydro#34]
The current judger keeps judging although the submission is wrong. Is there a way to stop it?
ex) for each subtask, when one testcase goes wrong, skips all testcase in that subtask and marks as  wrong.
![image](https://user-images.githubusercontent.com/48399106/100538874-b0943f00-3275-11eb-849e-f278b83687a9.png)

**Comment by undefined-moe** [comment]
should work in the latest version.
