### ISSUE TITLE
为什么安装了vjudge远端评测题还是提交时没有代码语言可以选择

### ISSUE THREAD

**Issue by xxmwyy** [hydro-dev/Hydro#341]
为什么安装了vjudge远端评测题还是提交时没有代码语言可以选择

**Comment by xxmwyy** [comment]
> 为什么安装了vjudge远端评测题还是提交时没有代码语言可以选择

**Comment by pandadtdyy** [comment]
在使用vjudge前请确保自己有足够的智力与专注度查看文档的每一处信息。
