### ISSUE TITLE
[Bug Report] ui-default v4.34.39 markdown 表格边框不易识别, 与底色太过接近

### ISSUE THREAD

**Issue by Dynesshely** [hydro-dev/Hydro#342]

**Comment by undefined-moe** [comment]
是否有样图

**Comment by Dynesshely** [comment]
![image](https://user-images.githubusercontent.com/50760269/162567571-b2877477-71e2-4efd-bfb6-2f7c551263d0.png)

**Comment by Dynesshely** [comment]
下方原先是表格

**Comment by Dynesshely** [comment]
![image](https://user-images.githubusercontent.com/50760269/162567595-89c938d6-9ed5-4502-87d0-30bdf1b6c2ed.png)

这是浅色效果

**Comment by undefined-moe** [comment]
dark mode 的调色问题比较多, 暂时不准备处理。

**Comment by Dynesshely** [comment]
好
