### ISSUE TITLE
【功能建议】建议加入对ldap用户接入功能

### ISSUE THREAD

**Issue by cxy5014** [hydro-dev/Hydro#350]
建议加入对ldap用户接入功能
方便域内用户统一身份管理

**Comment by pandadtdyy** [comment]
hydro提供了oauth接入模式 可以自行根据您的ldap编写插件 插件可参考`packages/oauth-with-github`

**Comment by undefined-moe** [comment]
是否能够详细描述一下需求场景以及具体需要同步哪些数据

**Comment by cxy5014** [comment]
在实验室内，通过Windows域控制器控制局域网内所有计算机，统一管理帐户，需要可以使用windows AD内samaccountname作为帐户名，继承Domain Admin的管理员权限。

**Comment by undefined-moe** [comment]
但是我寻思这套系统本来就没支持装在Windows上啊 🤔

**Comment by cxy5014** [comment]
我想您可能误会了我的意思了。我的意思是通过Windows的域控制系统来进行登录管理。
可以参考nextcloud（ https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ldap.html ）

**Comment by undefined-moe** [comment]
没有用过不是很懂  
也没有可用的测试环境 估计不会考虑提供官方实现
