### ISSUE TITLE
题库是否可以提供

### ISSUE THREAD

**Issue by lincolnred8** [hydro-dev/Hydro#357]
RT

**Comment by undefined-moe** [comment]
群文件和 https://hydro.ac/d/tk/p

**Comment by lincolnred8** [comment]
需要购买？

**Comment by undefined-moe** [comment]
部分题目免费提供。  
如预算不足，可选择自行出题，编辑题面，写 std 和 gen，上传，共花费零元。

**Comment by lincolnred8** [comment]
题库打包一共是多少钱啊？

还有，支持 SQL 评测吗

**Comment by undefined-moe** [comment]
没有内置 SQL 支持。但提供了相关接口可供自行定义评测逻辑。（参照评测设置 `langs` 选项或是 `user_extra_files` 的 `compile.sh` 及 `execute.sh`）

我们建议提问前先仔细阅读文档及系统设置中的选项。

**Comment by lincolnred8** [comment]
嗯。那么第一个问题呢？全部打包好的题目一共多少钱呢？毕竟整理很耗费精力的。

**Comment by undefined-moe** [comment]
参照上文及文档。作为开源软件系统，Hydro 不提供任何消费建议。
