### ISSUE TITLE
Guests available to make problems?

### ISSUE THREAD

**Issue by junukwon7** [hydro-dev/Hydro#38]
I installed hydro using the bash file on Hyper-v Ubuntu20 and found out that I can make problems although I didn't log in.
![image](https://user-images.githubusercontent.com/48399106/103263200-86f04400-49ea-11eb-8122-bd2360ef093b.png)
![image](https://user-images.githubusercontent.com/48399106/103263223-95d6f680-49ea-11eb-96c5-8eb69af734fb.png)

**Comment by undefined-moe** [comment]
Is this a display problem?
Please check the permission and privilege for userid 0 and 1.

**Comment by undefined-moe** [comment]
I have found the problem.
The owner of domain `system` was set to Guest(0) ,which should be Hydro(1).

You can execute 
`global.Hydro.model.domain.edit('system',{owner:1})`
in hydro interactive shell to hot fix this problem.

**Comment by junukwon7** [comment]
> I have found the problem.
> The owner of domain `system` was set to Guest(0) ,which should be Hydro(1).
> 
> You can execute
> `global.Hydro.model.domain.edit('system',{owner:1})`
> in hydro interactive shell to hot fix this problem.

`hydro interactive shell`? Is there a shell in hydro(public page)?

**Comment by undefined-moe** [comment]
Run hydrooj in the terminal and then you'll get a shell. All input started with `@`  will be executed directly.

**Comment by junukwon7** [comment]
> Run hydrooj in the terminal and then you'll get a shell. All input started with `@` will be executed directly.

Thanks!
