### ISSUE TITLE
记忆上次提交评测的语言

### ISSUE THREAD

**Issue by zirnc** [hydro-dev/Hydro#390]
提交的语言基本上是不会改来改去的吧，如果能记忆上一次提交的语言的话就不用每次都去选择语言了。

**Comment by undefined-moe** [comment]
有个东西叫偏好设置。

**Comment by zirnc** [comment]
![image](https://user-images.githubusercontent.com/42088872/179941949-37e7049b-65bb-4bd3-9bd3-823afd859bb3.png)
然后呢...提交代码还是 C 语言的编译器啊。
（等我回复了之后再 close 也不迟）

**Comment by zirnc** [comment]
也许是我没说清楚，这是在 CodeForces 子域下出现的。

**Comment by undefined-moe** [comment]
说明你点开的题目不支持你偏好的语言提交（可能是remotejudge题目，也可能题目上传者做了限制）

**Comment by zirnc** [comment]
所以在 RemoteJudge 这种情况下记忆上次的会比较好啊。

**Comment by undefined-moe** [comment]
记忆的话两个语言谁说了算？记忆的语言不可用怎么办？是不是还得做一个list让你对几十个语言的偏好度排序一下？

短期内不会考虑此问题。

**Comment by zirnc** [comment]
如果你觉得记忆不可行的话，那 RemoteJudge 这个体验问题怎么解决呢？
或者可以在不同的域使用不同的偏好设置？
总之，每次交代码都要留心语言确实不太便捷，毕竟其它平台都没有这种问题。

**Comment by undefined-moe** [comment]
现在偏好 C++ 时，会在 Codeforces 中自动选择 `Clang++17 Diagnostics`。

**Comment by Macesuted** [comment]
说实话一般没有人会用 clang diagnostics 交题吧，那个更多是查错而不是用于正常的提交。

我觉得也许用其他几个 G++ 的版本会更合适吧。

**Comment by undefined-moe** [comment]
复杂

**Comment by pandadtdyy** [comment]
每个域允许的语言不同，目前没有一个较好的存储方案，如果我有2000个不同语言的域，要怎么记录？此处没有一个较好的解决方案，如果你认为你的解决方案够优雅够快，prs welcome

**Comment by zirnc** [comment]
不知道发生了什么，但是现在在 CF 域里对于 C 和 C++ 的编译器检测挺准确的，解决了我的问题。感谢。
