### ISSUE TITLE
关于训练的bug | 建议

### ISSUE THREAD

**Issue by kaptree** [hydro-dev/Hydro#409]
## 一点小建议

如果其中的某道题被隐藏了，那么就不能进入训练，希望OJ能对**没有权限查看隐藏题目的成员先过滤掉训练中隐藏的题目**，然后可以正常访问

**Comment by undefined-moe** [comment]
- 如果一个章节的题目全部被隐藏，如何处理？直接标记章节为已完成？
- 如果整个训练的题目全部被隐藏，如何处理？

**Comment by kaptree** [comment]
## 一、章节的题目全部被隐藏
我认为可以存在这个章节，但是展开内容为空，但是一些有题目权限的管理员是能看到的

## 二、整个训练题目全部隐藏
一样的有这些章节，但是没有权限的同学是不能查看的，即内容展开为空

我觉得这是有场景存在的：
加入群体A正在进行训练赛，而题目就是从**一些题单**拉取的（例如每个题单拉一题），那么对于不参加比赛，而专注训练的群体B发现，大部分题单都进不去了，这显然是不合理的
