### ISSUE TITLE
题目标题的 TeX 代码仅在“最新题目”渲染

### ISSUE THREAD

**Issue by H-J-Granger** [hydro-dev/Hydro#411]
譬如 <https://hydro.ac/d/euler/> 内的“最新题目”中可看到 P801 的标题可被渲染；

但无论是 <https://hydro.ac/d/euler/p?page=17> 还是 <https://hydro.ac/d/euler/p/P801> 都无法渲染。

**Comment by undefined-moe** [comment]
所有标题均无计划支持富文本。
