### ISSUE TITLE
[Feature Request] 希望比赛可以添加封面

### ISSUE THREAD

**Issue by Patricky-Tau** [hydro-dev/Hydro#418]
🚀 理由、目的
-------

比赛的预览图既可以快速指出比赛类型，也可以告明赞助商云云。
这样的特性是十分精美的。

🎉 备选方案
------

或至少提供各种颜色，并同时给出比赛标签以便分类。

----

🙏 有劳了！

**Comment by undefined-moe** [comment]
PRs welcome.

**Comment by pandadtdyy** [comment]
Such as luogu, atcoder, uoj
![image](https://user-images.githubusercontent.com/15662967/186096243-0257af69-5310-4a33-8d77-f937ed4b423f.png)
![image](https://user-images.githubusercontent.com/15662967/186096283-c1d22894-a0c9-4884-bfa4-a6c4f6db8fb3.png)
![image](https://user-images.githubusercontent.com/15662967/186096173-f6a77cd5-043d-4b68-a4a5-d65782589cda.png)

I think contest type is showed in tag, sponsor can show on title, it is a unnecessary enhancement.

**Comment by Patricky-Tau** [comment]
🎉 感谢二位的回复！我将尝试实现之。
