### ISSUE TITLE
All user manage page

### ISSUE THREAD

**Issue by LuoShaoyinn** [hydro-dev/Hydro#438]
I couldn't find a page to manage all users  ( list all registed users and change someone's password )  although logged in the SU user. Dashboard-Userpriv page might help, but not enough. Is there any other page to manage user all over the website ( **not inside a single domain** ) ?

**Comment by pandadtdyy** [comment]
We think change someone's password over the website is not a safe operation. You need to use CLI to edit it.

**Comment by undefined-moe** [comment]
This might be taken into consideration but we currently suggests to use the backend shell as it is guaranteed to be secure. Recently we added a `sudo mode` feature, and we are planning to enable forced 2FA verification for superusers.

**Comment by LuoShaoyinn** [comment]
I'll take your suggestion though it's hard to teach my OI teacher using SSH and mongdb shell. Logging in via ssh under the window is also inconvenient because hydro-cli must run under sudoer, but sudoers are usually configured as blocking password authorization. I'm willing to test new features, but I probably won't be able to develop this project myself because I can almost only write C/C++.

**Comment by undefined-moe** [comment]
Windows10 includes a builtin ssh client (I'm not sure about older windows versions), which also accepts `~/.ssh/id_rsa` for authentication (strongly recommend to disable password auth for **all** users). I also suggests configuring a smtp account for password recovery.

**Comment by LuoShaoyinn** [comment]
Right. I forget to configure a SMTP  account. This should solve my problem perfectly. Thank you.
