### ISSUE TITLE
[Bug] 关于 OI 赛制中在线编程模式下自测代码无法查看结果

### ISSUE THREAD

**Issue by Molmin** [hydro-dev/Hydro#451]
如题。

**原因分析：** 自测提交发出的请求中含有 input 和 pretest 属性，其余数据与直接提交代码是相同的。OI 赛制下普通用户无法查看提交记录的评测结果，故无法查看到自测结果。

**修复建议：** 查看提交记录评测结果时，检测 pretest 参数是否为 true，再判断是否反馈数据。

望修复。

还有这个好像也挂了：<https://hydro.ac/ide>

**Comment by pandadtdyy** [comment]
IDE何处报错麻烦给个截图或者log，目前没有收到任何报错

**Comment by Molmin** [comment]
![](//hydro.ac/file/3309/123.png)

这是一个普通用户在OI赛制比赛中的 IDE，点击运行后显示 submitted但是输出区域没有任何反应

**Comment by Molmin** [comment]
图片链接：hydro.ac/file/3309/123.png

**Comment by pandadtdyy** [comment]
指的是 https://hydro.ac/ide 何处报错麻烦给个截图或者log （）

**Comment by pandadtdyy** [comment]
OI赛制全局禁止查看任何记录 需等待 #448 解决

**Comment by Molmin** [comment]
https://hydro.ac/file/3309/%E6%8D%95%E8%8E%B7.PNG
