### ISSUE TITLE
官站的批量注册账号和在线IDE功能能不能下放到社区版，感觉还是非常有用的，谢谢！

### ISSUE THREAD

**Issue by muyichenfeng** [hydro-dev/Hydro#455]
官站的批量注册账号和在线IDE功能能不能下放到社区版，感觉还是非常有用的，谢谢！

**Comment by undefined-moe** [comment]
你可能在找：控制面板 -> 导入用户

**Comment by muyichenfeng** [comment]
> 你可能在找：控制面板 -> 导入用户

官站的提供前缀即可生成特定数量的账户并且密码随机非常实用，导入用户功能制作账号信息较麻烦，谢谢

**Comment by pandadtdyy** [comment]
你要找的是不是excel

**Comment by undefined-moe** [comment]
https://github.com/hydro-dev/hydro-dev.github.io/pull/50/files#diff-503b480e31ab823526afaa24f421da994db18f3ca90ea2bec7e653dc50010eb5R24
