### ISSUE TITLE
【bug】hydro（PID=1）账户可以登录

### ISSUE THREAD

**Issue by w1010t** [hydro-dev/Hydro#460]
1、SU可以用菜单-切换用户不输入密码就可以登录别人账号（我给了我同学SU，他给我号JC了）
2、通过切换用户功能可以切换到hydro用户（不是说没法登录的吗！）
3、通过指令可以给hydro一个密码，接着就可以登录了

**Comment by undefined-moe** [comment]
![image](https://user-images.githubusercontent.com/29992205/200496560-58a317e7-0c0d-4d31-84bc-0f0041625869.png)
