### ISSUE TITLE
出现System Error

### ISSUE THREAD

**Issue by Bingxiusmall** [hydro-dev/Hydro#466]
自己新建了一道题，提交SE
https://hydro.ac/d/GXOJ/record/63874f662d0d63504376deca

**Comment by HayatoOvO** [comment]
Maybe your topic file is **too large.** And your memory usage is too large. Maybe you should open your evaluation stack a little wider.

In addition, this problem should be raised in “hello, HydroOJ” or “HydroOJ user groups”.

**Comment by undefined-moe** [comment]
I'm unable to reproduce this issue. closing now.
Feel free to re-open it if you are sure if there's a problem.

**Comment by Bingxiusmall** [comment]
How to edit evaluation stack?Probably it's because that.

**Comment by HayatoOvO** [comment]
> How to edit evaluation stack?Probably it's because that.

Please go to the "setting_limits" column on the "manage/setting" page to search for it in your webpage version of OnlineJudge.

**Comment by Bingxiusmall** [comment]
Where?Can you give me an example?(like www.???.???/??????)

**Comment by Bingxiusmall** [comment]
Where?Can you give me an example?(like www.???.???/??????)
