### ISSUE TITLE
Hydro v4.4.4 Community 中的异常 System Error

### ISSUE THREAD

**Issue by shine-yu-student** [hydro-dev/Hydro#467]
我校oj网站的Hydro版本更新至v4.4.4时，出现了大量的 `System Error` 。

所有的 `System Error` 的原因均显示为 `text.replace is not a function` 。

以下为一些截图。

![image](https://user-images.githubusercontent.com/105355837/205556206-8e3ab56c-0ac6-4bc8-ab6c-2165092aa8c6.png)

![image](https://user-images.githubusercontent.com/105355837/205556260-056b21ce-31b2-4fad-8df4-52390a88728e.png)

![image](https://user-images.githubusercontent.com/105355837/205556377-8cb9a841-63a4-4c90-bdc3-884cdefd77bc.png)

**Comment by undefined-moe** [comment]
commit d29bd22249ed47ef577f3c771d386b2326c8929f already fixes this problem. please upgrade to `hydrojudge@^3.1.10`.
