### ISSUE TITLE
修改smtp密码后，保存刷新，还是显示未更改

### ISSUE THREAD

**Issue by hiifong** [hydro-dev/Hydro#469]
![image](https://user-images.githubusercontent.com/89133723/206622627-840a14b9-7afd-43c7-b4ad-01932d44496f.png)

**Comment by pandadtdyy** [comment]
有没有可能 这是提示你你在修改其他设置的时候不会修改他

**Comment by hiifong** [comment]
> 有没有可能 这是提示你你在修改其他设置的时候不会修改他

开启注册需要邮件时报错
![image](https://user-images.githubusercontent.com/89133723/206628693-eef290af-4083-41fa-86aa-5f8f35077b74.png)

**Comment by undefined-moe** [comment]
SMTP 协议为标准协议实现，此处不提供教学，请自行检查配置项填写。如遇到问题可参照 [百度](https://baidu.com) 或 [必应](https://cn.bing.com/)

**Comment by hiifong** [comment]
> SMTP 协议为标准协议实现，此处不提供教学，请自行检查配置项填写。如遇到问题可参照 [百度](https://baidu.com) 或 [必应](https://cn.bing.com/)

这里使用的是飞书的域名邮箱服务，我使用在Gitea等其他软件没有问题
![image](https://user-images.githubusercontent.com/89133723/206629376-c650059e-1533-4447-809e-17fc803ec0ce.png)

**Comment by hiifong** [comment]
> > SMTP 协议为标准协议实现，此处不提供教学，请自行检查配置项填写。如遇到问题可参照 [百度](https://baidu.com) 或 [必应](https://cn.bing.com/)
> 
> 这里使用的是飞书的域名邮箱服务，我使用在Gitea等其他软件没有问题 ![image](https://user-images.githubusercontent.com/89133723/206629376-c650059e-1533-4447-809e-17fc803ec0ce.png)

这里是我的配置：
![image](https://user-images.githubusercontent.com/89133723/206630193-337e4498-5481-4b43-a316-74879d544ff8.png)

**Comment by undefined-moe** [comment]
飞书邮箱可正常使用，建议自查相关配置是否正确
目前已知可以正常使用的服务有：

- QQ 邮箱
- 腾讯企业邮
- 网易 163 邮箱
- Zoho Mail
- Outlook
- Zeptomail
- 飞书域名邮箱(feishu.cn)

**Comment by hiifong** [comment]
> 很抱歉，我未使用过飞书域名邮箱，无法为您提供相关协助。 目前已知可以正常使用的服务有：
> 
> * QQ 邮箱
> * 腾讯企业邮
> * 网易 163 邮箱
> * Zoho Mail
> * Outlook
> * Zeptomail

换QQ邮箱可以了，现在应该是不支持飞书邮箱吧，希望未来可以支持一下

**Comment by pandadtdyy** [comment]
<img width="963" alt="image" src="https://user-images.githubusercontent.com/15662967/206634106-30b0f618-975c-4cda-a4a2-23a86d14fac2.png">
用户配置问题我们不予解答。

**Comment by hiifong** [comment]
> <img width="963" alt="image" src="https://user-images.githubusercontent.com/15662967/206634106-30b0f618-975c-4cda-a4a2-23a86d14fac2.png">
> 用户配置问题我们不予解答。

感谢您的回答
