### ISSUE TITLE
栈太小了咋开栈啊

### ISSUE THREAD

**Issue by ZRZRING** [hydro-dev/Hydro#47]
rt，对一条链dfs的时候老re，别的oj没问题

**Comment by Macesuted** [comment]
如果您使用的Hydro系统部署在Linux下，应该是不会出现爆栈情况的。

如果您使用那个的Hydro系统没有部署在Linux下，您可能需要尝试使用G++指令开栈空间。

**Comment by undefined-moe** [comment]
在Linux下，默认的栈空间限制为8MiB。  
请按以下步骤操作：

- 关闭沙箱服务
- 使用 `ulimit -s unlimited` 解除栈空间限制
- 启动沙箱服务

提示：您可以在页面底端的系统状态页面内，将鼠标悬停在相应评测机的内存信息上以查看当前生效的栈空间限制。

**Comment by ZRZRING** [comment]
> 如果您使用的Hydro系统部署在Linux下，应该是不会出现爆栈情况的。
> 
> 如果您使用那个的Hydro系统没有部署在Linux下，您可能需要尝试使用G++指令开栈空间。

哦我是在vijos.org上用的

**Comment by undefined-moe** [comment]
> 哦我是在vijos.org上用的

请提供评测记录链接

**Comment by ZRZRING** [comment]
https://vijos.org/d/zrzring/records/60082df7f413621b7a35d99b
https://vijos.org/d/zrzring/records/60082bccf413621b7a35d994
https://vijos.org/d/zrzring/records/60082a1ef413621b7335ceca
https://vijos.org/d/zrzring/records/600828e1f413621b7b35dd4f
https://vijos.org/d/zrzring/records/60082892f413621b7a35d8f3

**Comment by undefined-moe** [comment]
已解除栈空间限制，请检查是否生效。

**Comment by ZRZRING** [comment]
> 已解除栈空间限制，请检查是否生效。

谢谢，问题已解决
