### ISSUE TITLE
HydroJS 4.4.4 在登录的时候崩溃了

### ISSUE THREAD

**Issue by Lixuannan** [hydro-dev/Hydro#471]
崩溃的图片是这样的：
<img width="1440" alt="截屏2022-12-11 20 00 08" src="https://user-images.githubusercontent.com/87345363/206902521-38fe7bb6-3640-4a9c-9098-0bb3a4eb7fd4.png">
$\huge{非常急，求助 undefine}$

**Comment by undefined-moe** [comment]
不处理由用户插件导致的问题。
