### ISSUE TITLE
[Feature Request] 增强赛时提醒功能

### ISSUE THREAD

**Issue by pt3155420267** [hydro-dev/Hydro#475]
比赛过程中如果出现题面更改的情况，比较难及时通知到参与比赛的用户，虽然项目中已有通过批量私信参与比赛的用户提醒功能，不过还是希望能够加强一下，可以像CodeForces那样弹窗提醒。

https://github.com/hydro-dev/Hydro/blob/b7a398db6f5f1e9359e321279dd447fce6913080/packages/hydrooj/src/handler/contest.ts#L212

**Comment by undefined-moe** [comment]
already implemented.
