### ISSUE TITLE
[Bug] 题目详情页内嵌 pdf 文件无法显示

### ISSUE THREAD

**Issue by Molmin** [hydro-dev/Hydro#486]
导入 pdf 文件后，若 url 最后没有斜杠则可以正常显示，否则无法正常显示

例如 `http://localhost/p/test` 可以正常显示，而 `http://localhost/p/test/` 无法正常显示

访问 `http://localhost/p/test` 时，请求的文件地址是 `http://localhost/p/24/file/A.pdf?noDisposition=1`

访问 `http://localhost/p/test/` 时，请求的文件地址是 `http://localhost/p/test/24/file/A.pdf?noDisposition=1`

经测试，hydro 主站也有此 bug

**Comment by wuxianucw** [comment]
这不是 bug，这是预料之中的表现。

这个问题在很早之前开发组内部已经讨论过，得出的结论是访问的 URL 应不以 `/` 结尾。
