### ISSUE TITLE
题目内置视频、pdf预览能否进行优化

### ISSUE THREAD

**Issue by theLucius7** [hydro-dev/Hydro#487]
当较大视频播放和pdf预览的时候，需要花费较长加载时间，并且消耗很多流量，能否进行优化

**Comment by pandadtdyy** [comment]
文件的加载速度取决于用户下载速度，用户加载速度取决于服务器速度，hydro无法在文件加载不上的情况下渲染文件，如果需要播放较大视频，我们推荐使用 `@[bilibili](BVxxx)` 的方式引入外站视频，如果你的服务器小水管不够速度让用户下载，你可以考虑将文件放置于直链网盘等地方使用 `@[pdf](https://.../a.pdf)`引入，但文件安全性和是否会泄漏不受hydro保护。

**Comment by undefined-moe** [comment]
把你的服务器升级到百兆带宽就快了。
