### ISSUE TITLE
[Help] 如何将一言的API改为自定义的API

### ISSUE THREAD

**Issue by orangezsclite** [hydro-dev/Hydro#488]
请问如何将Hydro部署后的主页的一言的API改为自定义的API？
我想改成这个GitHub项目里的API
[SDLYYZ/Tangokoto](https://github.com/SDLYYZ/Tangokoto)
谢谢！

**Comment by undefined-moe** [comment]
建议参照源码自行编写相关模块。此处不提供教程。
