### ISSUE TITLE
[新功能]希望能关闭个人主页，或者让个人主页只变成本人可看

### ISSUE THREAD

**Issue by liaojiqing2012** [hydro-dev/Hydro#492]
学生利用个人主页传递代码，取代了私信功能。

**Comment by pandadtdyy** [comment]
如果想作弊方法有点无穷无尽，不是一个很好的处理方案，开发组近期已将比赛期间只允许访问比赛页面和代码相似度检验列入即将上线功能内。

**Comment by orangezsclite** [comment]
> 如果想作弊方法有点无穷无尽，不是一个很好的处理方案，开发组近期已将比赛期间只允许访问比赛页面和代码相似度检验列入即将上线功能内。

不懂就问，使用了代码相似度检验之后学生会不会直接大改特改代码结构然后交上去然后就绕过了代码相似度检验。。。~~说实话我感觉人工还是比较好~~就是有点累

**Comment by undefined-moe** [comment]
这里再提供一个方案：可以截图上传到个人头像。

**Comment by mcoi-dev** [comment]
> 这里再提供一个方案：可以截图上传到个人头像。

艹，还有一个方案，自己临时搭建一个网站（虚拟机内网穿透），然后把地址放到显示名里

**Comment by zhblue** [comment]
建议用线下PK的方式解决抄袭问题 ；）
