### ISSUE TITLE
About Outlook

### ISSUE THREAD

**Issue by RonenWen** [hydro-dev/Hydro#495]
Oj似乎无法使用Outlook发送邮件，我不确定是我的设置问题还是程序的问题或者需要在outlook中执行一些特别的设置。
我使用了如下配置：

- 发件服务器地址：smtp.office365.com
- 端口：587
- 是否SSL：否
- 签名：为我的信箱地址

我能确保我的邮件账号密码无误
如果有相关的解决办法，感激不尽！
参考链接：https://hydro.js.org/docs/install/smtp/

**Comment by pandadtdyy** [comment]
outlook经测试是正常使用的，请自行根据发件时的相关报错处理具体问题。
