### ISSUE TITLE
Dependencies for evaluation

### ISSUE THREAD

**Issue by junukwon7** [hydro-dev/Hydro#53]
The dependency settings work well for scoring.
```
subtask: 
  time: 
  memory: 
  if: [0]
```
but the evaluation doesn't consider the dependencies.
![image](https://user-images.githubusercontent.com/48399106/108482464-dcefb280-72dc-11eb-91e2-0f9bc4a4a165.png)
In this problem, there are two subtasks 0(1-11) and 1(12-17). And subtask 1 has the term if:[0] so the submission above gets total 0 points. However, the judge evaluates all tcs in subtask 1 although the submission was already proved wrong.

Is there a solution for it?
Thanks

**Comment by undefined-moe** [comment]
please check if it's fixed in the latest version.

**Comment by undefined-moe** [comment]
Maybe I misunderstood.
Evaluation of each subtask is concurrently. So it might not consider subtask dependencies.

**Comment by undefined-moe** [comment]
Should be already fixed.
