### ISSUE TITLE
插件删除残留问题

### ISSUE THREAD

**Issue by FelixYu2021202** [hydro-dev/Hydro#536]
删除了一个插件后，启用它的账户仍然在启用状态而且无法停止启用。

求助

**Comment by FelixYu2021202** [comment]
给一个建议就是说增加一个页面显示自己所有启用的插件（包括被作者删除的插件也就是残留的插件），可以停止启用

**Comment by pandadtdyy** [comment]
用户在尝试拉取不存在的插件时会删除用户对该插件的启用。
