### ISSUE TITLE
关于开发模式编译失败的问题

### ISSUE THREAD

**Issue by mcoi-dev** [hydro-dev/Hydro#538]
本来想要用win开个hydro开发模式整个活，结果发现报错无法编译，具体好像是这个REPO的一个更改被删除了，于是编译失败。

这个REPO的commit：`https://github.com/Mango/emitter.git#commit=41ab8a3956269c7ed468bde50203e15b3274152f`

有没有解决办法或者分享一下预编译的版本？

**Comment by pandadtdyy** [comment]
请先检查你的网络连接。
<img width="893" alt="image" src="https://user-images.githubusercontent.com/15662967/225274258-52fe0da8-27d7-47d8-8852-674484604b5c.png">

**Comment by mcoi-dev** [comment]
但是我试过，能Ping上github，然后clone  https://github.com/Mango/emitter.git#commit=41ab8a3956269c7ed468bde50203e15b3274152f 的时候说被重定向到https://github.com/Mango/emitter.git了，有没有办法绕过重定向检查？
