### ISSUE TITLE
[Feature Request] 比赛自定义题目分数倍率

### ISSUE THREAD

**Issue by BlackPanda24** [hydro-dev/Hydro#539]
希望可以增加自定义题目分数倍率功能。

**Comment by undefined-moe** [comment]
1. 是否有已有赛制依赖于此功能？
2. 是否有具体的应用场景？
3. 是否有其他实现方案？

**Comment by BlackPanda24** [comment]
1.此功能可以用于IOI、OI和乐多赛制。
2.乐多赛制由于分数会随提交次数减少，赛时可能有需求增加分数倍率。
3.洛谷等OJ有实现此功能

**Comment by undefined-moe** [comment]
1 中所述为 【依赖】，即无此功能无法正常使用，而非【可以用于】。
2 应用场景需要明确而非【可能有需求】，乐多赛成绩为赛制内部计算，与题目分数倍率无关。

**Comment by undefined-moe** [comment]
closed due to inactivity.
