### ISSUE TITLE
[Feature Request] 接收邮件验证码以来跳过认证器验证

### ISSUE THREAD

**Issue by smallfangqwq** [hydro-dev/Hydro#543]
接收邮件验证码以来跳过认证器验证

**Comment by pandadtdyy** [comment]
如果拥有用户的密码，可能可以使用同一密码解开用户的邮箱。一个用户不应该只有一个认证器，更推荐在启用认证器的同时启用 Authenticator App。

**Comment by smallfangqwq** [comment]
那应该在仅有一个认证器时提供其他方案跳过认证。

**Comment by pandadtdyy** [comment]
> 那应该在仅有一个认证器时提供其他方案跳过认证。

未来会加入重置密码关闭所有认证器。
