### ISSUE TITLE
[Question]端口映射

### ISSUE THREAD

**Issue by Xiuyuan121** [hydro-dev/Hydro#593]
如果我要进行端口映射到外网且购买了域名后，该如何操作？
而且如果在同一台主机上还有docker同样想要映射的话，又该怎么做呢？

**Comment by ReiAccept** [comment]
首先这个问题不该在 Hydro 这提问，其次您应该出门左转 frp 或者使用 Wireguard 对一台有公网 IP 的服务器组网后转发
