### ISSUE TITLE
如果你有注意过的话 正在进行和即将开始的比赛是用红色和蓝色标记的

### ISSUE THREAD

**Issue by followWind-moe** [hydro-dev/Hydro#595]
如果你有注意过的话 正在进行和即将开始的比赛是用红色和蓝色标记的

_Originally posted by @undefined-moe in https://github.com/hydro-dev/Hydro/issues/594#issuecomment-1595712647_
            距离比赛开始时间超过七天的比赛并不会有颜色显示，且和已经结束的比赛类似，不太好作区分。

**Comment by pandadtdyy** [comment]
You can continue discussing it in the last pr and reopen it if you think it's necessary instead of opening a new one.
