### ISSUE TITLE
【新功能请求】对于 vjudge 的新增加 OJ 请求

### ISSUE THREAD

**Issue by tianbiandeshenghuo** [hydro-dev/Hydro#596]
目前使用的较多的 OJ 主要是 [洛谷](https://luogu.com.cn)、[CodeForces](codeforces.com) 和 [AtCoder](atcoder.jp) 。现在，Hydro 已经实现了前两个 OJ 的远程评测。那么，能否开发 AtCoder 的远程呢？

**Comment by pandadtdyy** [comment]
根据 [AtCoder 的 TOS](https://atcoder.jp/tos) ， AtCoder 不允许多人共用ID进行评测的行为。 暂时无法开发，您可以直接前往 AtCoder 官网直接下载测试数据。

**Comment by tianbiandeshenghuo** [comment]
已收到邮件，感谢您的回复~

**Comment by Molmin** [comment]
> 根据 [AtCoder 的 TOS](https://atcoder.jp/tos) ， AtCoder 不允许多人共用ID进行评测的行为。 暂时无法开发，您可以直接前往 AtCoder 官网直接下载测试数据。

问个问题：那洛谷是和 AtCoder 合作了吗

**Comment by tianbiandeshenghuo** [comment]
已收到邮件，感谢您的回复~

**Comment by pandadtdyy** [comment]
> > 根据 [AtCoder 的 TOS](https://atcoder.jp/tos) ， AtCoder 不允许多人共用ID进行评测的行为。 暂时无法开发，您可以直接前往 AtCoder 官网直接下载测试数据。
> 
> 问个问题：那洛谷是和 AtCoder 合作了吗

kkk去过线下。
