### ISSUE TITLE
关于 Remote Judge

### ISSUE THREAD

**Issue by xcx0902** [hydro-dev/Hydro#600]
这玩意有没有一个官方指南啊。

找了半天都没有。

**Comment by xcx0902** [comment]
最好详细一点的（就是所有列出所有安装命令、方法的）

**Comment by Lyricus233** [comment]
https://hydro.ac/d/faqs/p/13

**Comment by xcx0902** [comment]
thanks



在 2023-07-01 09:10:48，"BlackPanda" ***@***.***> 写道：

https://hydro.ac/d/faqs/p/13

**Comment by pandadtdyy** [comment]
首先，文档里是有的，其次，如果你没找到，我们不建议看不懂文档的同学部署相关插件。
