### ISSUE TITLE
一些关于讨论的 Bug

### ISSUE THREAD

**Issue by Molmin** [hydro-dev/Hydro#615]
1. 我是该域 root 角色但是无法编辑讨论下的评论或讨论下的评论下的回复
   
   <https://github.com/hydro-dev/Hydro/blob/master/packages/hydrooj/src/handler/discussion.ts#L272>

   <https://github.com/hydro-dev/Hydro/blob/master/packages/hydrooj/src/handler/discussion.ts#L312>
   
   （一定要是这个评论的所有者？）

2. 拥有 删除讨论中自己的回复 的权限的用户无法删除自己的回复

   <https://github.com/hydro-dev/Hydro/blob/master/packages/hydrooj/src/handler/discussion.ts#L283-L288>

3. 评论若被更改过就会在右侧显示已修改但是该评论下的回复也会显示已修改（这个不是很重要）

**Comment by undefined-moe** [comment]
1. 暂时保持此行为不变
2. 无法复现
3. 在 f46d8bf2 中修复

**Comment by Molmin** [comment]
Bug 1 在 [这里](https://hydro.ac/d/miltest/discuss/64b3cb4a50bcb9d548d1d262)

用 uid 21914 无法删除下面的回复

https://github.com/hydro-dev/Hydro/blob/f46d8bf224dbc1b9d21181ae13c0356637010d00/packages/hydrooj/src/handler/discussion.ts#L287

可能应为 `PERM_DELETE_DISCUSSION_REPLY_SELF`?
