### ISSUE TITLE
[Feature Request] 可以手动指定是否放榜

### ISSUE THREAD

**Issue by gtn1024** [hydro-dev/Hydro#623]
添加一个选项，在比赛结束时，如果设置了封榜，可以手动控制是否放榜。

**Comment by pandadtdyy** [comment]
<img width="631" alt="image" src="https://github.com/hydro-dev/Hydro/assets/15662967/43461498-ad2f-410f-aa73-8d04a4f5ba15">

**Comment by gtn1024** [comment]
Thanks!
