### ISSUE TITLE
vjudge/codeforces: 1776 场比赛没有爬取

### ISSUE THREAD

**Issue by Molmin** [hydro-dev/Hydro#625]
包括 hydro 主站同样没有爬取：https://hydro.ac/d/codeforces/p?page=169

https://codeforces.com/contest/1776

**Comment by pandadtdyy** [comment]
![8D8A253C-D7DD-4635-AB9B-4832226767D1](https://github.com/hydro-dev/Hydro/assets/15662967/83eeb892-8015-4e52-8c12-073ab257f8fd)
我这边看是有Hydro能正常爬取的， 可能是当时cf没有在problemset里放1776，如果你要我给你发个zip
