### ISSUE TITLE
排名有问题

### ISSUE THREAD

**Issue by tjc1216** [hydro-dev/Hydro#647]
![](https://cdn.luogu.com.cn/upload/image_hosting/as5p6f0z.png)
有一些同学的比赛会突然变很多
www.mfstem.org

**Comment by pandadtdyy** [comment]
请提供详细信息。

**Comment by tjc1216** [comment]
有一些同学明明比了很多比赛却不显示
www.mfstem.org



在 2023-08-21 22:10:00，"panda" ***@***.***> 写道：

请提供详细信息。

**Comment by Molmin** [comment]
> 有一些同学明明比了很多比赛却不显示 [www.mfstem.org](http://www.mfstem.org) 在 2023-08-21 22:10:00，"panda" ***@***.***> 写道： 请提供详细信息。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

1. 你这个链接根本看不到排名
2. 你比赛开没开rated
3. 比赛太多但是没有参加较新的比赛的时候比赛分会较低

**Comment by tjc1216** [comment]
谢谢



在 2023-08-22 19:39:33，"Milmon" ***@***.***> 写道：

有一些同学明明比了很多比赛却不显示 www.mfstem.org 在 2023-08-21 22:10:00，"panda" @.> 写道： 请提供详细信息。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

你这个链接根本看不到排名
你比赛开没开rated
比赛太多但是没有参加较新的比赛的时候比赛分会较低
