### ISSUE TITLE
关于 vjudge

### ISSUE THREAD

**Issue by Lixuannan** [hydro-dev/Hydro#648]
近期在 OJ 上开启了 vjudge 插件，使用 remotejudge 功能进行很多 OJ 题目的评测。这个功能的用户体验很不错。但仍存在一个痛点：不支持 AtCoder，希望能尽快支持针对 AtCoder 的 RemoteJudge

**Comment by pandadtdyy** [comment]
根据 [AtCoder 的 TOS](https://atcoder.jp/tos) ， AtCoder 不允许多人共用ID进行评测的行为。 暂时无法开发，您可以直接前往 AtCoder 官网直接下载测试数据。
