### ISSUE TITLE
关于跨域题目复制的题目附件问题

### ISSUE THREAD

**Issue by immccn123** [hydro-dev/Hydro#661]
在不同域之间复制的题目应该显示原题目的文件（预期行为），即题目附件（文件功能应该是这么用的）。

![图片](https://github.com/hydro-dev/Hydro/assets/41335471/78c69e77-0130-4c73-9a52-2fb31659b46d)

这个地方我认为应当显示 原题目 的附件。

或者说为了实现不同的需求需要更复杂的逻辑（？

**Comment by undefined-moe** [comment]
其实可以显示一个文件列表的。~~但是有点麻烦就懒得做了~~

**Comment by undefined-moe** [comment]
应当已经在最新版本中可用。
