### ISSUE TITLE
[Feature Request] 批量添加作业题目

### ISSUE THREAD

**Issue by qtlwc** [hydro-dev/Hydro#666]
创建作业时添加题目需要一个一个等待预览加载出来才能添加；  
希望可以批量输入以逗号分隔的题目清单；  
另外也同步在图库界面增加一个复制题目编号的功能（格式就是导入作业的格式）。

其次，希望可以将题库界面增加一个按题目名/PID……排序的功能。

**Comment by undefined-moe** [comment]
按照题目名排序有什么作用吗（？

**Comment by Molmin** [comment]
> 创建作业时添加题目需要一个一个等待预览加载出来才能添加； 希望可以批量输入以逗号分隔的题目清单； 另外也同步在图库界面增加一个复制题目编号的功能（格式就是导入作业的格式）。
> 
> 其次，希望可以将题库界面增加一个按题目名/PID……排序的功能。

其实可以开兼容模式复制id列表，操作好在切回去（）

**Comment by undefined-moe** [comment]
批量粘贴题号已于 #712 实现，在 UI 4.49.3 中发布。
