### ISSUE TITLE
批量删除题目的时候，题目对应的discussion不会被删除（数据库层面

### ISSUE THREAD

**Issue by nooooocato** [hydro-dev/Hydro#671]
这会在进入 **讨论** 页面的时候，报id错误

手动删库修好了 idk why

日志里面会提示一个哈希id找不着，我推测是这样滴，等我找机会复现：）

**Comment by nooooocato** [comment]
[mongodb-out.log](https://github.com/hydro-dev/Hydro/files/12894089/mongodb-out.log)
[hydrooj-out.log](https://github.com/hydro-dev/Hydro/files/12894090/hydrooj-out.log)
附上日志ww

**Comment by undefined-moe** [comment]
删了比赛 讨论没删 找不到比赛了 烂了

**Comment by nooooocato** [comment]
> 删了比赛 讨论没删 找不到比赛了 烂了

草，我以为是我大规模导入导出题目的锅…………

**Comment by undefined-moe** [comment]
fixed in a9b2f68d2d9bf180d7ea05dfe0cd2e8867e71cc8
