### ISSUE TITLE
請教自建伺服器 ，python turtle 類的題目如何配置?

### ISSUE THREAD

**Issue by dailinyang** [hydro-dev/Hydro#684]

**Comment by undefined-moe** [comment]
使用 `nix build github:hydro-dev/nix-channel#judge` 构建完整的 rootfs，将其（含 `/nix` 目录）映射至沙箱目录下，题目配置遵照官示例。

**Comment by Tivonfeng** [comment]
请问您python turtle的题目配置成功了吗？求教

**Comment by dailinyang** [comment]
沒有

Tivonfeng ***@***.***>於 2024年1月23日 週二，下午6:59寫道：
