### ISSUE TITLE
开发组外提问：Hydro讨论bug

### ISSUE THREAD

**Issue by hetao6899411** [hydro-dev/Hydro#697]
如果讨论曾今发表在了某个题目或者比赛的讨论节点，当题目或比赛被删除，那么就会发生讨论区崩溃的现象。

**Comment by ChengChen128** [comment]
> 如果讨论曾今发表在了某个题目或者比赛的讨论节点，当题目或比赛被删除，那么就会发生讨论区崩溃的现象。

删数据库

**Comment by pandadtdyy** [comment]
请更新版本。
