### ISSUE TITLE
cgroup failed to set memory limit open 

### ISSUE THREAD

**Issue by yviscool** [hydro-dev/Hydro#698]
提交的时候出现:

Compile Error 0ms 0KiB
execve: cgroup failed to set memory limit open /sys/fs/cgroup/executor_server/1780426089/memory.max: permission denied

**Comment by undefined-moe** [comment]
https://docs.hydro.ac/plugins/hydrojudge.html#%E5%86%85%E5%AD%98%E8%AE%A1%E9%87%8F%E4%B8%8D%E5%87%86%E7%A1%AE 请参照此处开启 cgroup v1。
