### ISSUE TITLE
首页 ranking 有 排名 但点击排名标签就提示 "对不起，此域中没有用户。 "

### ISSUE THREAD

**Issue by yviscool** [hydro-dev/Hydro#700]
![image](https://github.com/hydro-dev/Hydro/assets/20163909/db24baf8-bea3-4b82-bf5f-2de3f7b96300)
![image](https://github.com/hydro-dev/Hydro/assets/20163909/407ffbf7-fd73-4e3b-8670-4e121cd08001)

但是管理用户里面能看到这些人的信息, 评测记录也有他们的做题记录. 这是为何?

**Comment by undefined-moe** [comment]
此数据非实时更新。请等待一天后再查看。
