### ISSUE TITLE
关于 session

### ISSUE THREAD

**Issue by Molmin** [hydro-dev/Hydro#714]
在同一个 session 上登录、退登不会改变 session，这会直接导致一些问题：机房里一台打开过某 Hydro 实例的浏览器经过分发系统到整个机房每台电脑（可能表述不那么准确，大致意思），此时若一台电脑登上某个账号，所有的电脑都会登上这个账号。虽然使用已经用过的电脑分发到整个机房不是那么合理，但是我还是感觉这个设计不那么好。（举个例子：隔壁洛谷退登登录都会刷新 sessionId。）

**Comment by undefined-moe** [comment]
尽管没有登录用户，仍有一些临时信息需要储存（语言偏好等），无法做到在未登录时完全销毁 session 。

**Comment by Molmin** [comment]
> 尽管没有登录用户，仍有一些临时信息需要储存（语言偏好等），无法做到在未登录时完全销毁 session 。

那可能可以更新 sessionId 再继承之前的语言偏好？

**Comment by Molmin** [comment]
@undefined-moe 为什么现在刚登录一刷新就退登了。。
