### ISSUE TITLE
[Feature Request] Codeforces 个人绑定账号支持

### ISSUE THREAD

**Issue by shine-yu-student** [hydro-dev/Hydro#716]
众所周知，CF 使用了 CF 导致 CF 同一个账号的大量 RMJ 会被拒绝评测。

而隔壁 vjudge 提供了使用个人帐号进行评测的功能。

为了减轻账号压力，这个功能是很有用的。

**Comment by undefined-moe** [comment]
鉴于此功能的实现复杂性及本系统的定位，官方暂不会推出此功能。

我们欢迎您自行实现并提交 Pull Request。
