### ISSUE TITLE
讨论权限问题

### ISSUE THREAD

**Issue by Macesuted** [hydro-dev/Hydro#72]
![image](https://user-images.githubusercontent.com/57275149/112817704-51282d80-90b5-11eb-9be0-b7184b4d9bef.png)

可能是由于更新的原因？同时讨论被强制 PIN（即那个选项框无法更改）。

同时普通用户发的讨论希望能对管理员开放设置为“置顶”等的权限。

**Comment by undefined-moe** [comment]
无法复现此问题，请检查权限组是否正确配置
