### ISSUE TITLE
[Frontend] Rendering failed when table contains math formula with `|`

### ISSUE THREAD

**Issue by HeRaNO** [hydro-dev/Hydro#720]
With table:

```markdown
| 1    | 2    | $|x|$ |
| ---- | ---- | ----- |
| a    | b    | c     |
```

On Typora, it is rendered as:

![result](https://github.com/hydro-dev/Hydro/assets/18643142/41f738eb-17bf-44a1-8f55-5c373de50db5)

But on Hydro, it's rendered as (the right part of the image):

![hydro](https://github.com/hydro-dev/Hydro/assets/18643142/040091a2-5dad-409c-9958-8c232c8a7a54)

I think the result of Typora meets the requirement.

P.S. On Lyrio and Github, the table renders failed, too.

**Comment by pandadtdyy** [comment]
| 1    | 2    | $\|x\|$ |
| ---- | ---- | ----- |
| a    | b    | c     |

https://github.github.com/gfm/#example-200

**Comment by HeRaNO** [comment]
> 1	2	
> |
> �
> |
> a	b	c
> https://github.github.com/gfm/#example-200

Sure it's a way to bypass, but

1. Hydro can't handle $\|x\|$ correctly.
![QQ截图20240125085337](https://github.com/hydro-dev/Hydro/assets/18643142/38d7f8a6-e579-48c0-a198-047d55ca4f4f)
It should be an absolute value symbol, not a norm symbol.
2. For the semantics aspect, maybe we should parse the math formula first, and then the table.

**Comment by pandadtdyy** [comment]
> > 1	2
> > |
> > �
> > |
> > a	b	c
> > https://github.github.com/gfm/#example-200
> 
> Sure it's a way to bypass, but
> 
> 1. Hydro can't handle |x| correctly.
>    ![QQ截图20240125085337](https://github.com/hydro-dev/Hydro/assets/18643142/38d7f8a6-e579-48c0-a198-047d55ca4f4f)
>    It should be an absolute value symbol, not a norm symbol.
> 2. For the semantics aspect, maybe we should parse the math formula first, and then the table.

Hydro use markdown-it as markdown parser. It follows  GFM spec, See https://github.com/markdown-it/markdown-it/issues/808. But the editor on the screenshot doesn’t use same parser. We suggest to use Monaco Editor because we can not find a better editor although the vditor’s parser is a s**t.

**Comment by HeRaNO** [comment]
> > > 1	2
> > > |
> > > �
> > > |
> > > a	b	c
> > > https://github.github.com/gfm/#example-200
> > 
> > 
> > Sure it's a way to bypass, but
> > 
> > 1. Hydro can't handle |x| correctly.
> >    ![QQ截图20240125085337](https://private-user-images.githubusercontent.com/18643142/299503841-38d7f8a6-e579-48c0-a198-047d55ca4f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNTIzNDgsIm5iZiI6MTcwNjE1MjA0OCwicGF0aCI6Ii8xODY0MzE0Mi8yOTk1MDM4NDEtMzhkN2Y4YTYtZTU3OS00OGMwLWExOTgtMDQ3ZDU1Y2E0ZjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAzMDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYzgyODIxMGI3ZDU1MGU2YjI5MTQ2MDAxZmRkOGQ4NDYwNDNlYTU4M2M0MDUzNjYyOWZmYjliNzA4M2Q1NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-WTY1_GLn8LS6j8gzIPoMyHNIt1ng8Q7P-lpeUZE0MM)
> >    It should be an absolute value symbol, not a norm symbol.
> > 2. For the semantics aspect, maybe we should parse the math formula first, and then the table.
> 
> Hydro use markdown-it as markdown parser. It follows GFM spec, See [markdown-it/markdown-it#808](https://github.com/markdown-it/markdown-it/issues/808). But the editor on the screenshot doesn’t use same parser. We suggest to use Monaco Editor because we can not find a better editor although the vditor’s parser is a s**t.

OK I see, thx

**Comment by undefined-moe** [comment]
related: https://github.com/Vanessa219/vditor/issues/1550
