### ISSUE TITLE
如何禁用站内消息? 

### ISSUE THREAD

**Issue by yviscool** [hydro-dev/Hydro#734]
有很多用户闲着没事能无限复制粘贴不停发送站内信息

**Comment by pandadtdyy** [comment]
控制面板 用户权限 将DEFAULT USER的私信权限关闭。

![104C5A0CA6743E9BC51906D31B45D4FE](https://github.com/hydro-dev/Hydro/assets/15662967/ebc98a2c-eccb-48d9-a49b-31a1eca22ba6)

**Comment by yviscool** [comment]
> 控制面板 用户权限 将DEFAULT USER的私信权限关闭。
> 
> ![104C5A0CA6743E9BC51906D31B45D4FE](https://private-user-images.githubusercontent.com/15662967/308058974-ebc98a2c-eccb-48d9-a49b-31a1eca22ba6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTY1NDcsIm5iZiI6MTcwOTAxNjI0NywicGF0aCI6Ii8xNTY2Mjk2Ny8zMDgwNTg5NzQtZWJjOThhMmMtZWNjYi00OGQ5LWE0OWItMzFhMWVjYTIyYmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA2NDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YzViMzZkZWQxODRiYmU4OTYwOTQ1OTFhMmYxMTM2M2ViYjNkYjI5MzVlYjExNzUwZGQ5OGYyNmYxNzI1YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EcZxuzy6JnXNWLtMBW-Ltcha1L29egqe3XygnrqfQSc)

老铁你这个回复速度也太快了,  平时都没别的事情吗?
