### ISSUE TITLE
请问如何找到网络访问日志？

### ISSUE THREAD

**Issue by klarkxy** [hydro-dev/Hydro#737]
系统：Ubuntu 22.04.4 LTS

使用脚本默认安装的。

请问该去哪个地方找系统访问日志？或者有没有比较好的调试API的办法？

**Comment by undefined-moe** [comment]
访问日志由 caddy 负责记录，请参照 Caddyfile 配置。
调试 API 可使用 Postman / Hoppscotch 等工具。
