### ISSUE TITLE
插件中的pages文件夹里的内容未生效

### ISSUE THREAD

**Issue by klarkxy** [hydro-dev/Hydro#741]
![image](https://github.com/hydro-dev/Hydro/assets/6316992/0aabbb0b-cc49-4d78-be36-54353f4b0c47)

文件夹内情况如图。
templates中的内容都是生效的，后端内容也是生效。
我查了一下源码，是需要在插件中也进行initPageLoader么？
是需要在哪里调用？

**Comment by undefined-moe** [comment]
请使用 `frontend/` 而非 `pages/` 。
同时，推荐使用 `.page.ts` 以便于类型推导。

**Comment by klarkxy** [comment]
> 请使用 `frontend/` 而非 `pages/` 。 同时，推荐使用 `.page.ts` 以便于类型推导。

感谢，目前已经引用进去了。
但是另一个问题是，我该怎么`import { NamedPage } from 'vj/misc/Page';`
这个`vj/*`我看了下是`packages/ui-default/*`，但是我用`yarn add -D @hydrooj/ui-default`之后，并不能`import { NamedPage } from '@hydrooj/ui-default/misc/Page';`
这里要怎么处理。

**Comment by undefined-moe** [comment]
`import { WhateverYouWant } from '@hydrooj/ui-default';`
