### ISSUE TITLE
题目AC率计算问题

### ISSUE THREAD

**Issue by Macesuted** [hydro-dev/Hydro#76]
现在的题目 `nAccept` 表示通过此题的用户数量， `nSubmit` 表示通过此题的总提交数量。而 AC 率由 `nAccept/nSubmit` 得到，通常不能反映真实情况。

希望能够将 `nAccept` 改为总的 AC 的提交数量，或是将 `nSubmit` 改为提交过此题的用户数量。即让 `nAccept` 和 `nSubmit` 同样表示提交量或是提交过的用户量。总之应该让单位统一。

**Comment by undefined-moe** [comment]
RFC: 将 `nSubmit` 改为用户首次AC前的所有提交数量

**Comment by Macesuted** [comment]
> RFC: 将 `nSubmit` 改为用户首次AC前的所有提交数量

那是否有可能会大于 100%

**Comment by undefined-moe** [comment]
肯定是含AC那次提交的

**Comment by Macesuted** [comment]
我认为可以降低 problemStat 脚本的效率，让它近似于枚举每个用户在某题上的提交。

然后在正常情况下只需要在用户提交评测的时候查询是否曾 AC 过来判断就行吧（

**Comment by undefined-moe** [comment]
should be solved. closing this issue.
