### ISSUE TITLE
[bug] 排名展示个性签名有漏洞

### ISSUE THREAD

**Issue by Eletary** [hydro-dev/Hydro#767]
在个性签名开头加入<td></td>接下来的内容会溢出到开头（应该前提是 rk 前 100）。

如，将个签改为 `<td></td>![](/file/2579/meow.gif)`，效果如下：

![image](https://github.com/hydro-dev/Hydro/assets/86780576/0f9500b4-7541-41c8-a8e6-eec8680a1930)

不知道是否涉及代码安全问题。

**Comment by undefined-moe** [comment]
请再次测试

**Comment by Eletary** [comment]
目测已经修复
