### ISSUE TITLE
评测机输出信息过多，导致用户可以根据评测信息去骗分

### ISSUE THREAD

**Issue by Limorton** [hydro-dev/Hydro#78]
![image](https://user-images.githubusercontent.com/27600540/113086222-b5b6bb80-918d-11eb-98c2-3acf50154b84.png)

如上图，评测机的输出信息和标准答案都给提示了，在现有代码上，写几个 if 就能骗分了

**Comment by undefined-moe** [comment]
建议通过在单个测试点内设置多组测试数据来解决该问题。

**Comment by wheneveright** [comment]
把expect后面的去掉应该就好了

**Comment by Macesuted** [comment]
> 把expect后面的去掉应该就好了

那和没有反馈信息有啥区别么（

**Comment by wheneveright** [comment]
就输出几位比如expect 119*****这样

**Comment by Macesuted** [comment]
> 就输出几位比如expect 119*****这样

如果是这样的话，倒不如像 Luogu 那样只显示一个字符的信息。

**Comment by wheneveright** [comment]
说到底，其实用户骗分不是什么事情，都是自己的选择，loj都放开数据，所以不管就好了

**Comment by Macesuted** [comment]
> 说到底，其实用户骗分不是什么事情，都是自己的选择，loj都放开数据，所以不管就好了

也不能这么说吧。对于一些 OJ 来说数据的保密还是挺重要的。

不过我也觉得应该 wontfix，毕竟如果输出只有一个数，还能有很多其他方法获取输出的（比如通过故意 RE 来二分输入输出内容）。出题人应该考虑从题目方面解决这个问题。

**Comment by undefined-moe** [comment]
现已支持通过以下方式抑制detail输出：

独立评测机配置中设置 hosts[host].detail 为 false （全局有效）
题目配置文件中设置 detail 为 false
