### ISSUE TITLE
讨论 Pin 权限问题

### ISSUE THREAD

**Issue by Macesuted** [hydro-dev/Hydro#80]
我是全站管理员但是无法更改一个讨论的 Pin 状态。

@undefined-moe 您可以尝试一下我站上任意一个讨论。比如 <https://hydro.org.cn/discuss/60612f70a5b9d9df5879da52/edit>。

**Comment by Macesuted** [comment]
似乎还是不行？（

**Comment by undefined-moe** [comment]
你看看权限管理里面的pin discussion
