### ISSUE TITLE
如何搭建到二级目录

### ISSUE THREAD

**Issue by Godtokoo666** [hydro-dev/Hydro#810]
假设我的域名是abc.com。在这样一种场景下，我没有修改域名解析的权利，我需要在abc.com/oj目录下搭建hydrooj，使用nginx反代，反代是正常实现的，也就是访问具体的页面或静态资源是可以的。但是hydrooj基于反代实现的url，不会自动加上oj字段，导致静态资源以及链接不能正常展示，点击链接后，会跳转abc.com/xxx而不是abc.com/oj/xxx，所以如何进行配置，使得全站url得以更改。

**Comment by undefined-moe** [comment]
您好，暂不考虑支持该功能。
