### ISSUE TITLE
训练中的题目被删除后进入训练错误

### ISSUE THREAD

**Issue by HelkeNarmo** [hydro-dev/Hydro#815]
导致无法删除这个训练。
<img width="520" alt="image" src="https://github.com/hydro-dev/Hydro/assets/26002022/340d5cdf-ac58-4b7e-bb8e-18f560028627">

系统版本如下：
yarn list v1.22.22
warning package.json: No license field
├─ @hydrooj/a11y@0.0.1
├─ @hydrooj/fps-importer@1.5.11
├─ @hydrooj/hydrojudge@3.3.12
├─ @hydrooj/register@1.0.0
├─ @hydrooj/ui-default@4.50.1
├─ @hydrooj/utils@1.4.22
└─ hydrooj@4.12.2
   └─ @hydrooj/utils@1.4.23

**Comment by undefined-moe** [comment]
https://github.com/hydro-dev/hydro-dev.github.io/blob/docs/docs/user/domain.md?plain=1#L91
