### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by Rratic** [hydro-dev/Hydro#82]
东西太多做不过来/kk，过来说一下~~防止忘了~~
1. 建议给题解增加这样的特性：用户可以点赞(+1)/踩(-1)，分数<=-2时在24小时内题解会被移除
2. 建议补全性别（现在直接用Other概括），并加上`Unknown`

**Comment by Macesuted** [comment]
> 东西太多做不过来/kk，过来说一下~防止忘了~
> 
> 1. 建议给题解增加这样的特性：用户可以点赞(+1)/踩(-1)，分数<=-2时在24小时内题解会被移除
> 2. 建议补全性别（现在直接用Other概括），并加上`Unknown`

第一条有恶评风险。

第二条是什么意思？（

**Comment by Rratic** [comment]
@Macesuted 
> 第二条是什么意思？（

<https://github.com/LGBT-CN/LGBTQIA-In-China>
这不是您star过？

第一条是有示例的：scp官网就是这么运行的，没有出现什么问题。

考虑到OJ可能的低龄问题，可以改成：在<=-2后，经管理员审核后删除（可以减少审核量）

**Comment by undefined-moe** [comment]
题解将根据评分排序，无必要删除低分题解。

**Comment by Rratic** [comment]
@undefined-moe 问题就在于，题解可能出现违法之类情况，明白？

**Comment by Macesuted** [comment]
> @undefined-moe 问题就在于，题解可能出现违法之类情况，明白？

那讨论之类的也有可能吧

**Comment by Macesuted** [comment]
> @undefined-moe 问题就在于，题解可能出现违法之类情况，明白？

这应该是站点管理员所需要处理的不可避免的问题。

**Comment by undefined-moe** [comment]
建议通过 `solution/add` `discussion/add` 等钩子对接外部鉴别服务管理。
低分题解提交管理员审核极易造成 spam 且在多数情况下无作用。

**Comment by Rratic** [comment]
> 这应该是站点管理员所需要处理的不可避免的问题。

确实，但是如果OJ发展后，人数不够呢？个人认为打分给予了群体一个自调节机制

**Comment by Rratic** [comment]
建议3. 把yaml转成更现代的toml

**Comment by Macesuted** [comment]
> > 这应该是站点管理员所需要处理的不可避免的问题。
> 
> 确实，但是如果OJ发展后，人数不够呢？个人认为打分给予了群体一个自调节机制

但是打分仅能作为参考，如果题解确实有问题应该举报才对。

**Comment by undefined-moe** [comment]
> 确实，但是如果OJ发展后，人数不够呢？个人认为打分给予了群体一个自调节机制

若有需求请自行编写插件处理，core不会处理相关内容。

> 建议3. 把yaml转成更现代的toml

yaml 的应用相较 toml 更加广泛且对 javascript 特殊数据类型的支持更好。

**Comment by Rratic** [comment]
> 但是打分仅能作为参考，如果题解确实有问题应该举报才对。
~~对不起，我nt了~~

**Comment by Rratic** [comment]
> yaml 的应用相较 toml 更加广泛且对 javascript 特殊数据类型的支持更好。

toml是“一个像样的人类可读的格式，同时能无歧义地映射到哈希表”，其本质是yaml的简化和去歧义化。

> Talk is cheap,show me the code!

对不起，"东西太多做不过来/kk，过来说一下防止忘了"

**Comment by undefined-moe** [comment]
1. 我不认为 yaml 不可读。
2. 我不认为 toml 能够很好的支持 BigInt, Function, Regexp 等类型的序列化。

**Comment by Rratic** [comment]
az

**Comment by Rratic** [comment]
~~@Tom Preston-Werner 有活干了~~

**Comment by sparrowhe** [comment]
我认为toml很好

**Comment by sparrowhe** [comment]
> > @undefined-moe 问题就在于，题解可能出现违法之类情况，明白？
> 
> 这应该是站点管理员所需要处理的不可避免的问题。

可以接入内容审核

**Comment by Macesuted** [comment]
> > > @undefined-moe 问题就在于，题解可能出现违法之类情况，明白？
> > 
> > 
> > 这应该是站点管理员所需要处理的不可避免的问题。
> 
> 可以接入内容审核

这种东西我想官方应该没必要提供，用户可以自行写插件。

**Comment by sparrowhe** [comment]
只是提出一个能够减少人力的可行性的方案，具体实现可以再商榷
