### ISSUE TITLE
客观题中的填空题，如果出现双引号会出现页面渲染错误

### ISSUE THREAD

**Issue by fearlessxjdx** [hydro-dev/Hydro#826]
![image](https://github.com/hydro-dev/Hydro/assets/17431574/02f5aa20-e6b8-4381-91c6-2e1868fc5e40)

测试版本是4.48.24

**Comment by undefined-moe** [comment]
already fixed in https://github.com/hydro-dev/Hydro/commit/1c8a6ee9ab52f0e590ba179c8fe11d7220a8fd16
