### ISSUE TITLE
客观题中的多选题存在bug

### ISSUE THREAD

**Issue by fearlessxjdx** [hydro-dev/Hydro#828]
多选题一但提交之后，前端就会出现bug，调用了不存在的函数。

或者勾选一个选项后，点刷新，也同样出现这个问题，然后页面就会出现个转圈。

似乎bug只出现在只选一个选项的时候？

![image](https://github.com/hydro-dev/Hydro/assets/17431574/1a2a4707-d025-45f1-a820-1ebeff79fe25)

**Comment by undefined-moe** [comment]
already fixed in https://github.com/hydro-dev/Hydro/commit/1c8a6ee9ab52f0e590ba179c8fe11d7220a8fd16

**Comment by fearlessxjdx** [comment]
> already fixed in [1c8a6ee](https://github.com/hydro-dev/Hydro/commit/1c8a6ee9ab52f0e590ba179c8fe11d7220a8fd16)

@undefined-moe 哦，好的，方便推一下 yarn 吗？想修复下这个bug，非常感谢！
