### ISSUE TITLE
Codeforces Remote Judge 爬题中断

### ISSUE THREAD

**Issue by xcx0902** [hydro-dev/Hydro#832]
![image](https://github.com/hydro-dev/Hydro/assets/99001676/631fd24b-63f3-4e02-93ca-8c064f0426ae)

自从 08:57:43 连接错误开始，codeforces vjudge worker 便下线，oj 的控制面板中显示 `vjudge worker codeforces/***:`，即不在线，题目爬取也停止。提交仍可以正常评测。

希望的做法应该是，重新尝试连接，达到一定次数（如 10 次）仍未成功再下线。不然的话，每次遇到这种情况就要重启 oj，十分麻烦。

**Comment by undefined-moe** [comment]
PRs Welcome.

**Comment by undefined-moe** [comment]
在最新版本会每周重新进行题目拉取。
