### ISSUE TITLE
[BUG] 自测功能在部分系统下无法使用

### ISSUE THREAD

**Issue by yaoxi-std** [hydro-dev/Hydro#839]
macOS 下，点击运行后不出现任何结果。

<img width="669" alt="image" src="https://github.com/hydro-dev/Hydro/assets/57950207/29de1849-c77f-4d2e-8ca9-5de12cf5db0f">

`chrome://version` 信息：

Google Chrome | 126.0.6478.127 (Official Build) (arm64)
-- | --
Revision | a435861f0ca363a64f7485619ee5939833823fce-refs/branch-heads/6478@{#1592}
OS | macOS Version 14.3.1 (Build 23D60)
JavaScript | V8 12.6.228.21
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

在 Windows 下运行正常。

![image](https://github.com/hydro-dev/Hydro/assets/57950207/66e4d1a2-4fe5-4b5c-9590-de22ce0f72e8)

`chrome://version` 信息：

Microsoft Edge | 126.0.2592.87 (正式版本) (arm64)
-- | --
修订 | 883b9421f9ba9ce195934ad8d16cb5215b659245
Chromium 版本 | 126.0.6478.127
操作系统 | Windows 11 Version 22H2 (Build 22621.3007)
JavaScript | V8 12.6.19.7
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0

**Comment by pandadtdyy** [comment]
<img width="817" alt="image" src="https://github.com/hydro-dev/Hydro/assets/15662967/09a4186f-c5d5-4a76-80e1-44639f1d0355">
无法复现 请自行按 F12 打开开发工具查看报错是否因为 网络状况 导致 websocket 断开。

**Comment by pandadtdyy** [comment]
<img width="858" alt="image" src="https://github.com/hydro-dev/Hydro/assets/15662967/de44335d-15a7-43a1-ab34-a1385a97c8d8">
无法复现 请自行按 F12 打开开发工具查看报错是否因为 网络状况 导致 websocket 断开。

**Comment by yaoxi-std** [comment]
嗯，清缓存 + 关代理后正常了。抱歉，没想到会是网络的问题。

**Comment by yaoxi-std** [comment]
嗯，清缓存 + 关代理后正常了。抱歉，没想到会是网络的问题。
