### ISSUE TITLE
[Feature Request]支持在交互题使用Special Judge

### ISSUE THREAD

**Issue by Delovue** [hydro-dev/Hydro#844]
现题库交互题评测配置中无法选用Special Judge，直接改写配置文件显示不支持

**Comment by Molmin** [comment]
没懂，交互题为啥要 special judge，交互器不是可以直接返回评测结果吗

**Comment by Delovue** [comment]
> 没懂，交互题为啥要 special judge，交互器不是可以直接返回评测结果吗

想用自定义的计分方式，而非默认比较器
