### ISSUE TITLE
题目pid带有下划线时打不开

### ISSUE THREAD

**Issue by CuteMurasame** [hydro-dev/Hydro#848]
顺便问一下可不可以让 pid 可以包含下划线

（写了个 AtCoder vjudge，但是因为题目 pid 原因无法正常使用

**Comment by pandadtdyy** [comment]
根据 [AtCoder 的 TOS](https://atcoder.jp/tos) ， AtCoder 不允许多人共用ID进行评测的行为。 暂时无法开发，您可以直接前往 AtCoder 官网直接下载测试数据。

**Comment by CuteMurasame** [comment]
> 根据 [AtCoder 的 TOS](https://atcoder.jp/tos) ， AtCoder 不允许多人共用ID进行评测的行为。 暂时无法开发，您可以直接前往 AtCoder 官网直接下载测试数据。

所以 vjudge.net 是违规的？

（好像听说 kkk 联系了 atcoder，所以可以用 vjudge，hydro多久联系一下atcoder）
