### ISSUE TITLE
[Bug] The icon does not seem correct in dark mode

### ISSUE THREAD

**Issue by langningchen** [hydro-dev/Hydro#854]
![image](https://github.com/user-attachments/assets/6cda38df-e5bf-4ad3-804f-9a3200cf015a)
![image](https://github.com/user-attachments/assets/ed6ee218-06da-44b9-aae1-9407ffbd58c0)

The error icon (especially the eye) does not seem to be correct when the dark mode is enabled.

**Comment by laoshuikaixue** [comment]
This is an interesting question. Indeed, the area around the eyes should be filled with white; the black of the eyes overlaps with the background🤣
