### ISSUE TITLE
[Feature Request] 更改题面颜色以适配深色主题

### ISSUE THREAD

**Issue by laoshuikaixue** [hydro-dev/Hydro#859]
![20240811113651](https://github.com/user-attachments/assets/75b9d81f-d3da-4156-9f88-eeb477686250)

![20240811113725](https://github.com/user-attachments/assets/2dbda396-10b4-4075-b31c-419d6e267019)

如上图 在网上部分题目较旧 题面为HTML格式 指定了题面的颜色 导致深色主题无法看到题目

能否可以增加功能 当主题为深色时 将题面的#333333 #000000等深色的值反转 或者移除/禁用

**Comment by undefined-moe** [comment]
Markdown 中并无原生颜色相关 API  
若需处理，建议导入题目时移除 color 等样式。
