### ISSUE TITLE
在线编程模式代码编辑器不遵从深色模式设置

### ISSUE THREAD

**Issue by imnotlxy** [hydro-dev/Hydro#870]
Hydro OJ 整体采用了现代的前端设计，提供了浅色和深色模式支持。目前大部分页面的深色模式都是正常的，除了在线编程模式下的代码编辑器仍然为浅色。建议为其适配深色模式。

**Comment by undefined-moe** [comment]
在编辑器设置中选择一个深色主题是不是就可以了

**Comment by imnotlxy** [comment]
> 在编辑器设置中选择一个深色主题是不是就可以了

确实，真的可以耶！十分感谢！顺便问一下，题目编辑器能否调深色模式？

**Comment by Molmin** [comment]
> > 在编辑器设置中选择一个深色主题是不是就可以了
> 
> 确实，真的可以耶！十分感谢！顺便问一下，题目编辑器能否调深色模式？

偏好设置里面把编辑器换成 monaco

**Comment by imnotlxy** [comment]
感谢！
