### ISSUE TITLE
比赛中的隐藏题目中PDF内嵌会显示无相应权限

### ISSUE THREAD

**Issue by XiaoGeNekidora** [hydro-dev/Hydro#884]
如果在题目中嵌入附加文件中的PDF，再将题目设置为隐藏。将题目加入到比赛/作业中后嵌入的PDF在非管理员账号中会显示无相应权限。

期望结果：显示对应的PDF

可能原因是tid参数没有继续传递给文件下载的URL，导致判断为无权限

**Comment by pandadtdyy** [comment]
请认真查看文档，使用file://引用文件
