### ISSUE TITLE
题目统计页面的重测整题按钮没有二次确认

### ISSUE THREAD

**Issue by wood3** [hydro-dev/Hydro#888]
`/p/*/stat` 这个页面的重测整题按钮点了会立即全部重测所有记录，没有二次确认的弹窗。

**Comment by Molmin** [comment]
评测设置页面也没有

**Comment by wood3** [comment]
> 评测设置页面也没有

欸确实，所以是特意的特性？

**Comment by Molmin** [comment]
> > 评测设置页面也没有
> 
> 欸确实，所以是特意的特性？

我只是顺便说一下，一起修了
