### ISSUE TITLE
关于代码长度限制

### ISSUE THREAD

**Issue by guosoun** [hydro-dev/Hydro#893]
在 NOI 系列赛事中，代码长度限制通常为 100KB，但此 OJ 的限制为 64KB 左右，希望改为 100KB。

**Comment by undefined-moe** [comment]
是否有公开可参考的相关文件/规定等？

**Comment by guosoun** [comment]
- [关于NOI系列赛编程语言使用限制的规定](https://www.noi.cn/gynoi/tlgd/2011-04-14/710432.shtml) 中提到「每道题参赛程序源文件不得大于100KB」。
- [NOI2024笔试题库](https://www.noi.cn/xw/2024-07-01/827159.shtml) 中提到「35. NOI 系列赛中对程序源文件大小的默认限制是：小于 100KB」。

**Comment by Molmin** [comment]
试题 pdf 也会写，见 [NOIP 2022 试题 PDF](https://qoj.ac/[download.php](https://qoj.ac/download.php?type=attachments&id=1055&r=0)?type=attachments&id=1055&r=0) 的第一页注意事项的第六条

**Comment by undefined-moe** [comment]
https://github.com/hydro-dev/Hydro/commit/9fbab0164190cb8f8e05a7e29e17c65e94b53228
