### ISSUE TITLE
浏览题目时使用 OnlyOffice 阅读内嵌的 PDF 无法复制内容

### ISSUE THREAD

**Issue by RimuruChan** [hydro-dev/Hydro#898]
测试了 Edge 和 Firefox 都无法复制，而采用浏览器的内嵌阅读器是正常的（上传文件那里点开是浏览器内嵌的）。

题目链接：https://hydro.ac/d/hlutacm/p/290

**Comment by undefined-moe** [comment]
https://github.com/hydro-dev/Hydro/blob/master/packages/onlyoffice/index.ts#L29

**Comment by RimuruChan** [comment]
uhm，所以为什么 hydro 本站是不能复制的
