### ISSUE TITLE
关于”忽略行末空格与文件尾回车“

### ISSUE THREAD

**Issue by wood3** [hydro-dev/Hydro#903]
根据今年的 CSP-JS 评测结果，有同学在文件尾写 `\r`，导致最后 $0$ 分。

希望可以加入严格回车为 `\n` 的选项以适应 NOI 赛事评测。

当然这个也不急，因为正常没人会用 `\r` 作为结尾。

**Comment by undefined-moe** [comment]
这好抽象。
但是可以通过偷换沙箱环境内的 `/usr/bin/diff` 解决（？

**Comment by wood3** [comment]
> 这好抽象。 但是可以通过偷换沙箱环境内的 `/usr/bin/diff` 解决（？

可能可以，或者真要那么严格，我想到了似乎也可以做一个严格读换行的 spj 实现。

回头如果搞好了可以把这个 spj 丢到 testlib 的 preset 里面就好了。
