### ISSUE TITLE
多文件提交答案评测出错

### ISSUE THREAD

**Issue by bigmiaocat** [hydro-dev/Hydro#919]
拿以前AC的答案zip压缩包交到原题会提示Unzip failed.
在自己OJ和hydro.ac都出现这种情况
![截图 2024-12-14 14-40-33](https://github.com/user-attachments/assets/be8ded9a-eb06-47ac-91b7-d585921a79c0)

**Comment by undefined-moe** [comment]
fixed in 5ae557a95fcaa87e318fda1c54a5c2dc6437f63b
