### ISSUE TITLE
“营利性组织（培训机构等）需要支付少量授权费”不是合法的 AGPL 附加条款

### ISSUE THREAD

**Issue by ouuan** [hydro-dev/Hydro#95]
根据 AGPL 3.0 中的以下内容，如果我的理解没有出现偏差，“营利性组织（培训机构等）需要支付少量授权费”不是合法的 AGPL 附加条款：

https://github.com/hydro-dev/Hydro/blob/ebc2c7eedfb8fd4d0ee2f13085c4be519cea310d/LICENSE#L349-L384

https://github.com/hydro-dev/Hydro/blob/ebc2c7eedfb8fd4d0ee2f13085c4be519cea310d/LICENSE#L451-L457

并且附加条款可以在重分发时被删除：

https://github.com/hydro-dev/Hydro/blob/ebc2c7eedfb8fd4d0ee2f13085c4be519cea310d/LICENSE#L342-L347

从条款之外的道德层面来看，“营利性组织（培训机构等）需要支付少量授权费”是 non-[free](https://www.gnu.org/philosophy/free-sw.html) 的行为，与 AGPL 协议的精神完全不符，这样的附加条款是不合适的。

所以，我认为，依据现有条款，任何人，无论是否是营利性组织，都可以在遵守 AGPL 3.0 条款的前提下免费使用当前版本的 Hydro。

如果你需要对营利性组织收费，以下选择是可行的：

1. 不进行 AGPL 授权，使用一个 non-free license 仅对非营利性用途授权。但现有版本的 Hydro 以 AGPL 3.0 授权，relicense 仅对未来的更新有效而对现有版本无效。
2. 鼓励但不强求营利性组织付费。
3. 以 AGPL 和商业授权双重授权。这样的话使用者需要在遵循 AGPL 条款和付费这二者之间选其一。例如，如果要进行闭源处理，需要商业授权。

**Comment by undefined-moe** [comment]
感谢您指出此错误。将更改盈利模式以解决此问题。  

~~笑死，根本没人付钱~~

**Comment by wuxianucw** [comment]
感谢您在协议事宜方面为 Hydro 做出的相关贡献，我谨代表个人建议 Hydro 在 All Contributors 中列出您付出的努力，谢谢！

但我个人同样有一句忠告：在整活 PR 中利用他人无知实施 Off Topic 嘲讽是极其恶劣的行为。即使是 neo4j 这样的项目仍然出现过无效 AGPL 附加条款的失误，这并不值得羞耻。undefined 对国内版权意识的嘲讽与我们在法律事务上的无知并没有任何关系，更不构成对我们失误的辩护。您可以利用协议漏洞，但不应在完全无关的主题下发起不友善的攻击。

**Comment by ouuan** [comment]
是这样的，我当时得到的信息是在我提出本 issue 且在 fea6a6285f9cff1aa274923fc979fc656f94eeb1 中已修正后 Hydro 的 LICENSE 又修改成了在 LGPL 上加入禁止商用，我并没有意识到在我提醒后这种情况依然可以是非恶意的，我当时的判断是 Hydro 方面无视了我之前的提醒。如果第二次禁止商用依然是无意造成的，我的嘲讽确实不妥当。
